  const TRAILS = [
    
  {
    "id": 1,
    "slug": "hiking-trail-barzonja-jelinak-cvrsnica-mountain-bosnia-and-herzegovina",
    "name": "Vrh Jelinak (Čvrsnica)",
    "area": "Čvrsnica",
    "mountain": "Čvrsnica",
    "distanceKm": 5.5,
    "elevationM": 570,
    "durationH": 4.5,
    "startLat": 43.59084,
    "startLon": 17.47495,
    "routeType": "Povratna (isti put)",
    "destinations": ["Čvrsnica"],
    "tags": ["Čvrsnica", "Jelinak", "Park prirode Blidinje", "Blidinje", "Barzonja"],
    "description": "Uspon na Jelinak s Barzonje. Planinarenje grebenom s prelijepim vidicima na Blidinjsko Jezero, Vran Planinu i više predjele Čvrsnice. Greben Jelinka je ujedno i najljepši vidikovac na Blidinjsko jezero kojeg će te pronaći u Parku prirode Blidinje.",
    "gpx": "/gps/triglav-planika.gpx",
    "thumbnail": "images/hiking-trail-jelinak-cvrsnica-blidinje-nature-park-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza na vrh Jelinak u Parku prirode Blidinje s lijepim pogledom na Blidinjsko jezero."
  },
  {
    "id": 2,
    "slug": "hiking-trail-hajducka-vrata-cvrsnici-mountain-bosnia-and-herzegovina",
    "name": "Hajdučka Vrata (najlakša staza)",
    "area": "Čvrsnica",
    "mountain": "Čvrsnica",
    "distanceKm": 16.5,
    "elevationM": 700,
    "durationH": 7,
    "startLat": 43.67306,
    "startLon": 17.62273,
    "routeType": "Povratna (isti put)",
    "destinations": ["Hajdučka Vrata"],
    "tags": ["Planinarski dom Vilinac", "Hajdučka Vrata", "Zaglavlje", "Vitlenica", "Park Prirode Blidinje", "Trinjača", "Via Dinarica", "Čvrsnica"],
    "description": "Uspon do Hajdučkih Vrata najljepšom planinarskom stazom i pogled iza Vrata na kanjon dubok 1800m. Ova staza pri povratku ostavlja dojam kao da hodate nekom drugom zbog raznolikog planinskog pejzaža Čvrsnice.",
    "gpx": "/gps/velebit-premuziceva.gpx",
    "thumbnail": "images/hiking-trail-hajducka-vrata-cvrsnica-blidinje-nature-park-bosnia-and-herzegovina.jpg",
    "alt": "Najpopularnija planinarska staza na Balkanu do Hajdučkih Vrata u srcu Hercegovine. Najljepše planinarske staze u Bosni i Hercegovini."
  },
  {
    "id": 3,
    "slug": "hiking-trail-rujiste-zelena-glava-prenj-mountain-bosnia-and-herzegovina",
    "name": "Zelena Glava s Rujišta (Prenj)",
    "area": "Prenj",
    "mountain": "Prenj",
    "distanceKm": 27,
    "elevationM": 1450,
    "durationH": 11,
    "startLat": 43.46480,
    "startLon": 17.96286,
    "routeType": "Povratna (isti put)",
    "destinations": ["Prenj"],
    "tags": ["Prenj", "Zelena Glava", "Bijele Vode", "Jezerce", "Rujište", "Mostar", "Adnan Krilić"],
    "description": "Uspon na Zelenu Glavu s Rujišta. Dugotrajna staza koja prolazi lijepom dolinom u srcu Prenj planine. Zadnji koraci osigurani sajlom. Pogled s najvišeg vrha se prostire do svih prenjskih 2000-njaka. Mogućnost spavanja u Pl. domu Adnan Krilić i u Pl. skloništu Jezerce.",
    "gpx": "/gps/begunjscica-vrh.gpx",
    "thumbnail": "images/hiking-trail-zelena-glava-prenj-mountain-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza s Rujišta na Zelenu Glavu na Prenj planini koja je prava atrakcija u blizini Mostara."
  },
  {
    "id": 4,
    "slug": "hiking-trail-gornja-brela-pakline-biokovo-mountain-croatia",
    "name": "Pakline preko Šuplje Stine (Biokovo)",
    "area": "Biokovo",
    "mountain": "Biokovo",
    "distanceKm": 7,
    "elevationM": 480,
    "durationH": 4.5,
    "startLat": 43.38756,
    "startLon": 16.92941,
    "routeType": "Kružna",
    "destinations": ["Biokovo"],
    "tags": ["Biokovo", "Pakline", "Šuplja Stina", "Nevistina Stina", "Gornja Brela", "Biokovo Nature Park"],
    "description": "Jedna od najljepših planinarskih staza u Hrvatskoj. Svaki korak donosi nešto novo. Sklonište na Paklinama s pogledom na more kao iz snova.",
    "gpx": "/gps/klekovaca-greben.gpx",
    "thumbnail": "images/hiking-trail-biokovo-mountain-gornja-brela-pakline-croatia.jpg",
    "alt": "Najljepša planinarska staza na Biokovu te u Dalmaciji koja vodi na Pakline s pogledom na more i litice s druge strane. Najljepše planinarske staze u Hrvatskoj."
  },
  {
    "id": 5,
    "slug": "hiking-trail-podgradina-konj-kamesnica-mountain-bosnia-and-herzegovina",
    "name": "Podgradina - Konj (Kamešnica)",
    "area": "Kamešnica",
    "mountain": "Kamešnica",
    "distanceKm": 12.3,
    "elevationM": 1050,
    "durationH": 7.5,
    "startLat": 43.70852,
    "startLon": 16.96295,
    "routeType": "Povratna (isti put)",
    "destinations": ["Kamešnica"],
    "tags": ["Kamešnica", "Konj", "Pešino Vrilo", "Livno", "Buško Jezero", "Livanjsko Polje", "Podgradina"],
    "description": "Uspon na Konja. Staza koja vodi uz žubor potoka. Planinarsko sklonište i izvor, bukova šuma i neodoljiv vidikovac. Štenja grebenom do vrha.",
    "gpx": "/gps/sljeme-tomislavac.gpx",
    "thumbnail": "images/hiking-trail-kamesnica-mountain-podgradina-konj-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza Podgradina - Konj na planini Kamešnici. Atrakcija u okolici Livna."
  },
  {
    "id": 6,
    "slug": "hiking-trail-blidinje-veliki-vran-vran-mountain-bosnia-and-herzegovina",
    "name": "Hajdučke Vrleti - Veliki Vran",
    "area": "Vran",
    "mountain": "Vran",
    "distanceKm": 8,
    "elevationM": 840,
    "durationH": 4.5,
    "startLat": 43.65428,
    "startLon": 17.52940,
    "routeType": "Povratna (isti put)",
    "destinations": ["Vran"],
    "tags": ["Vran planina", "Veliki Vran", "Hajdučke Vrleti", "Hajdučko Vrilo", "Blidinje"],
    "description": "Planinarska staza koja vodi dijelom kroz borovu šumu a zatim po travnatim pašnjacima do najvišeg vrha Vran planine. Polazna točka u blizini poznatog restorana u Parku prirode Blidinje.",
    "gpx": "/gps/medvednica-hunjka.gpx",
    "thumbnail": "images/hiking-trail-vran-mountain-hajducke-vrleti-veliki-vran-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza do najvišeg vrha Vran Planine. Polazna točka pored popularnog restorana Hajdučke Vrleti u srcu Parka prirode Blidinje."
  },
  {
    "id": 7,
    "slug": "hiking-trail-glavas-sinjal-dinara-mountain-croatia-vrh-hrvatske",
    "name": "Vrh Hrvatske iz Glavaša (Dinara)",
    "area": "Dinara",
    "mountain": "Dinara",
    "distanceKm": 17.7,
    "elevationM": 1380,
    "durationH": 9,
    "startLat": 44.01117,
    "startLon": 16.41941,
    "routeType": "Povratna (isti put)",
    "destinations": ["Dinara"],
    "tags": ["Najviši vrh RH", "Glavaš", "Martinova košara", "Dinara", "Sinjal", "Sklonište Drago Grubać"],
    "description": "Najviši vrh RH sa skloništem i lijepim pogledom. Staza koja polazi blizu izvora rijeke Cetine i preko travnatih strmina vodi grebenom Dinare. Na stazi su srednjovjekovna utvrda i planinarsko sklonište.",
    "gpx": "/gps/dinara-sinjal.gpx",
    "thumbnail": "images/hiking-trail-dinara-mountain-glavas-vrh-hrvatske-croatia.jpg",
    "alt": "Planinarska staza na planini Dinari koja pored jedne srednjovjekovne utvrde i planinarskog skloništa vodi na najviši vrh Hrvatske."
  },
  {
    "id": 8,
    "slug": "hiking-trail-prisoje-vitrenik-tusnica-mountain-bosnia-and-herzegovina",
    "name": "Prisoje - Vitrenik (Tušnica)",
    "area": "Tušnica",
    "mountain": "Tušnica",
    "distanceKm": 13,
    "elevationM": 960,
    "durationH": 6,
    "startLat": 43.69434,
    "startLon": 17.08365,
    "routeType": "Kružna",
    "destinations": ["Tušnica"],
    "tags": ["Prisoje", "Dobrijevac", "Vitrenik", "Tušnica", "Buško jezero", "Livno", "Tomislavgrad"],
    "description": "Uspon na najviši vrh Tušnice, Vitrenik. Staza koja polazi iz Prisoja vodi do najvišeg vrha pored planinarskog doma Dobrijevac te prelijepim grebenom sve do najvišeg vrha Vitrenik (1697m). Pogled na Buško jezero cijelo vrijeme oduzima dah.",
    "gpx": "/gps/ostrovaca-uspon.gpx",
    "thumbnail": "images/hiking-trail-tusnica-mountain-prisoje-vitrenik-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza na Vitrenik, planina Tušnica. Staza koja polazi iz Prisoja i vrluda travnatim grebenom planine."
  },
  {
    "id": 9,
    "slug": "hiking-trail-satorsko-jezero-veliki-sator-sator-mountain-bosnia-and-herzegovina",
    "name": "Planina Šator (Jezero i vrh)",
    "area": "Šator",
    "mountain": "Šator",
    "distanceKm": 4.9,
    "elevationM": 380,
    "durationH": 3.5,
    "startLat": 44.16747,
    "startLon": 16.60200,
    "routeType": "Povratna (isti put)",
    "destinations": ["Šator"],
    "tags": ["Šator planina", "Šatorsko Jezero", "Bosansko Grahovo"],
    "description": "Obilazak Šatorskog jezera i uspon do najvišeg vrha ove planine uz prelijepe vidikovce na veliko jezero. Pristupni put je makadamski.",
    "gpx": "/gps/sator-jezero-vrh.gpx",
    "thumbnail": "images/hiking-trail-sator-mountain-satorsko-jezero-veliki-sator-bosnia-and-herzegovina.jpg",
    "alt": "Šatorsko jezero i najviši vrh Šatora na prelijepoj planinarskoj stazi"
  },
  {
    "id": 10,
    "slug": "hiking-trail-prijevor-maglic-trnovacko-jezero-maglic-mountain-bosnia-and-herzegovina",
    "name": "Prijevor - Maglić - Trnovačko jezero",
    "area": "Maglić",
    "mountain": "Maglić",
    "distanceKm": 13.5,
    "elevationM": 1200,
    "durationH": 7,
    "startLat": 43.28775,
    "startLon": 18.71666,
    "routeType": "Kružna",
    "destinations": ["Maglić"],
    "tags": ["Maglić", "Prijevor", "Sutjeska", "Trnovačko Jezero", "Tara", "Prašuma Perućica", "Vodopad Skakavac", "Tjentište"],
    "description": "Planinarska staza koja pri usponu ima i sajle za dodatno osiguranje. Najviši vrh BiH i pogled s njega na visoke crnogorske planine. Travnata prostranstva i Trnovačko jezero kao najljepši biser Balkana.",
    "gpx": "/gps/kozara-mrakovica.gpx",
    "thumbnail": "images/hiking-trail-maglic-mountain-prijevor-maglic-trnovacko-jezero-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza s Prijevora na Maglić. Kružna tura uz obilazak Trnovačkog jezera."
  },
  {
    "id": 11,
    "slug": "hiking-trail-vrgorac-sveti-rok-matokit-mountain-bosnia-and-herzegovina",
    "name": "Vrgorac - Sv. Rok (Matokit)",
    "area": "Matokit",
    "mountain": "Matokit",
    "distanceKm": 7.5,
    "elevationM": 790,
    "durationH": 5,
    "startLat": 43.20696,
    "startLon": 17.36823,
    "routeType": "Povratna (isti put)",
    "destinations": ["Matokit"],
    "tags": ["Matokit", "Sveti Rok", "Vrgorac"],
    "description": "Tipična dalmatinska planinarska staza preko kamenjara do na vrh. Staza polazi iz grada Vrgorca i vodi na najviši vrh Matokita, Sveti Rok.",
    "gpx": "/gps/ivanscica-vrh.gpx",
    "thumbnail": "images/hiking-trail-matokit-mountain-vrgorac-sveti-rok-croatia.jpg",
    "alt": "Planinarska staza Vrgorac - Sveti Rok. Matokit planina."
  },
  {
    "id": 12,
    "slug": "hiking-trail-kruzi-cincar-cincar-mountain-bosnia-and-herzegovina",
    "name": "Pl. dom Kruzi - Cincar",
    "area": "Cincar",
    "mountain": "Cincar",
    "distanceKm": 11.5,
    "elevationM": 780,
    "durationH": 6,
    "startLat": 43.87353,
    "startLon": 17.02449,
    "routeType": "Povratna (isti put)",
    "destinations": ["Cincar"],
    "tags": ["Cincar", "Livno", "Planinarski dom Kruzi", "Izvor Duman", "Divlji konji livno"],
    "description": "Jedinstvena planinarska staza koja od Planinarskog doma Kruzi vodi na najviši vrh Cincara. Staza vodi po visoravni gdje se prolazi pored mnogo krda divljih konja.",
    "gpx": "/gps/kamesnica-konj.gpx",
    "thumbnail": "images/hiking-trail-cincar-mountain-kruzi-cincar-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza Kruzi - Cincar. Posjeta divljim konjima na visoravni dok hodate gotovo uvijek moguća."
  },
  {
    "id": 13,
    "slug": "hiking-trail-zahum-idovac-radusa-mountain-bosnia-and-herzegovina",
    "name": "Zahum - Idovac (Raduša)",
    "area": "Raduša",
    "mountain": "Raduša",
    "distanceKm": 13,
    "elevationM": 810,
    "durationH": 6,
    "startLat": 43.83112,
    "startLon": 17.44995,
    "routeType": "Povratna (isti put)",
    "destinations": ["Raduša"],
    "tags": ["Raduša", "Zahum", "Felix staza", "Idovac", "Idovačko jezero", "Rama", "Ramsko jezero", "Diva Grabovčeva"],
    "description": "Planinarska staza na najviši vrh Raduše ispod kojeg se nalazi i istoimeno jezero. Blizu polazne točke se nalazi vidikovac na Ramsko jezero koji svakako vrijedi posjetiti.",
    "gpx": "/gps/cincar-vrh.gpx",
    "thumbnail": "images/hiking-trail-radusa-mountain-zahum-idovac-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza Zahum - Idovac na planini Raduši. Vidikovac na Ramsko jezero u blizini."
  },
  {
    "id": 14,
    "slug": "vranica-nadkrstac",
    "name": "Nadkrstac – Vranica",
    "area": "Vranica",
    "mountain": "Vranica",
    "distanceKm": 16,
    "elevationM": 900,
    "durationH": 7,
    "startLat": 43.98,
    "startLon": 17.62,
    "routeType": "Kružna",
    "destinations": ["Nadkrstac"],
    "tags": ["Zlatne kupole", "Prokoško jezero"],
    "description": "Zlatne kupole i travnati grebeni Vranice.",
    "gpx": "/gps/vranica-nadkrstac.gpx",
    "thumbnail": "images/thumbnails/vranica-nadkrstac.jpg"
  },
  {
    "id": 15,
    "slug": "matinski-vis",
    "name": "Matinski Vis uspon",
    "area": "Matinski Vis",
    "mountain": "Matinski Vis",
    "distanceKm": 8.2,
    "elevationM": 520,
    "durationH": 3.5,
    "startLat": 43.42,
    "startLon": 17.41,
    "routeType": "Povratna (isti put)",
    "destinations": ["Matinski Vis"],
    "tags": ["Matin grad", "Pogledi"],
    "description": "Kratka, ugodna ruta s pogledima.",
    "gpx": "/gps/matinski-vis.gpx",
    "thumbnail": "images/thumbnails/matinski-vis.jpg"
  },
  {
    "id": 16,
    "slug": "zavelim-vrh",
    "name": "Zavelim vrh",
    "area": "Zavelim",
    "mountain": "Zavelim",
    "distanceKm": 9.5,
    "elevationM": 600,
    "durationH": 4,
    "startLat": 43.4,
    "startLon": 17.27,
    "routeType": "Povratna (isti put)",
    "destinations": ["Zavelim"],
    "tags": ["Imotska krajina", "Kameniti prijevoj"],
    "description": "Kameniti prijevoji iznad Imotske krajine.",
    "gpx": "/gps/zavelim-vrh.gpx",
    "thumbnail": "images/thumbnails/zavelim-vrh.jpg"
  },
  {
    "id": 17,
    "slug": "golija-greben",
    "name": "Golija greben",
    "area": "Golija",
    "mountain": "Golija",
    "distanceKm": 13.5,
    "elevationM": 780,
    "durationH": 6,
    "startLat": 43.33,
    "startLon": 20.2,
    "routeType": "Kružna",
    "destinations": ["Golija"],
    "tags": ["Biosfera", "NP Golija"],
    "description": "Put kroz guste šume i travnate vrhove.",
    "gpx": "/gps/golija-greben.gpx",
    "thumbnail": "images/thumbnails/golija-greben.jpg"
  },
  {
    "id": 18,
    "slug": "stozer-vrh",
    "name": "Stožer vrh",
    "area": "Stožer",
    "mountain": "Stožer",
    "distanceKm": 10,
    "elevationM": 700,
    "durationH": 5,
    "startLat": 43.87,
    "startLon": 17.4,
    "routeType": "Povratna (isti put)",
    "destinations": ["Stožer"],
    "tags": ["Kupres", "Skijalište"],
    "description": "Planina iznad Kupresa s otvorenim vidicima.",
    "gpx": "/gps/stozer-vrh.gpx",
    "thumbnail": "images/thumbnails/stozer-vrh.jpg"
  },
  {
    "id": 19,
    "slug": "ljubusa-prijevoj",
    "name": "Ljubuša prijevoj",
    "area": "Ljubuša",
    "mountain": "Ljubuša",
    "distanceKm": 12,
    "elevationM": 500,
    "durationH": 5,
    "startLat": 43.79,
    "startLon": 17.43,
    "routeType": "Kružna",
    "destinations": ["Ljubuša"],
    "tags": ["Pašnjaci", "Kupreško"],
    "description": "Valoviti pašnjaci i blagi usponi.",
    "gpx": "/gps/ljubusa-prijevoj.gpx",
    "thumbnail": "images/thumbnails/ljubusa-prijevoj.jpg"
  },
  {
    "id": 20,
    "slug": "tusnica-greben",
    "name": "Tušnica greben",
    "area": "Tušnica",
    "mountain": "Tušnica",
    "distanceKm": 11.5,
    "elevationM": 640,
    "durationH": 5,
    "startLat": 43.74,
    "startLon": 17.01,
    "routeType": "Kružna",
    "destinations": ["Tušnica"],
    "tags": ["Livno", "Greben Tušnice"],
    "description": "Greben s pogledom na Livno.",
    "gpx": "/gps/tusnica-greben.gpx",
    "thumbnail": "images/thumbnails/tusnica-greben.jpg"
  },
  {
    "id": 21,
    "slug": "svilaja-bat",
    "name": "Svilaja – Bat",
    "area": "Svilaja",
    "mountain": "Svilaja",
    "distanceKm": 12.8,
    "elevationM": 880,
    "durationH": 6,
    "startLat": 43.7,
    "startLon": 16.49,
    "routeType": "Povratna (isti put)",
    "destinations": ["Bat"],
    "tags": ["Lećevića", "Zečje polje"],
    "description": "Kameniti vrhovi nad Dalmatinskom zagorom.",
    "gpx": "/gps/svilaja-bat.gpx",
    "thumbnail": "images/thumbnails/svilaja-bat.jpg"
  },
  {
    "id": 22,
    "slug": "biokovo-sveti-jure",
    "name": "Sveti Jure",
    "area": "Biokovo",
    "mountain": "Biokovo",
    "distanceKm": 8,
    "elevationM": 700,
    "durationH": 4.5,
    "startLat": 43.352,
    "startLon": 17.059,
    "routeType": "Povratna (isti put)",
    "destinations": ["Sveti Jure"],
    "tags": ["Biokovo Skywalk", "Ravni"],
    "description": "Krov Dalmacije s nevjerojatnim pogledima.",
    "gpx": "/gps/biokovo-sv-jure.gpx",
    "thumbnail": "images/thumbnails/biokovo-sveti-jure.jpg"
  },
  {
    "id": 23,
    "slug": "mosor-vickov-stup",
    "name": "Vickov stup krug",
    "area": "Mosor",
    "mountain": "Mosor",
    "distanceKm": 10,
    "elevationM": 820,
    "durationH": 5.5,
    "startLat": 43.52,
    "startLon": 16.62,
    "routeType": "Kružna",
    "destinations": ["Vickov stup"],
    "tags": ["Umberto Girometta", "Žlijeb"],
    "description": "Kružna staza po Mosoru, krševit teren.",
    "gpx": "/gps/mosor-vickov-stup.gpx",
    "thumbnail": "images/thumbnails/mosor-vickov-stup.jpg"
  },
  {
    "id": 24,
    "slug": "radusa-idovac",
    "name": "Raduša Idovac",
    "area": "Raduša",
    "mountain": "Raduša",
    "distanceKm": 14.5,
    "elevationM": 900,
    "durationH": 7,
    "startLat": 43.85,
    "startLon": 17.36,
    "routeType": "Povratna (isti put)",
    "destinations": ["Idovac"],
    "tags": ["Blidinje", "Raduša greben"],
    "description": "Prostrani travnjaci i grebeni.",
    "gpx": "/gps/radusa-idovac.gpx",
    "thumbnail": "images/thumbnails/radusa-idovac.jpg"
  },
  {
    "id": 25,
    "slug": "vran-veliki",
    "name": "Vran – Veliki Vran",
    "area": "Vran",
    "mountain": "Vran",
    "distanceKm": 12.2,
    "elevationM": 950,
    "durationH": 6,
    "startLat": 43.63,
    "startLon": 17.4,
    "routeType": "Povratna (isti put)",
    "destinations": ["Veliki Vran"],
    "tags": ["Masna Luka", "Blidinje"],
    "description": "Staza iznad Blidinjskog jezera.",
    "gpx": "/gps/vran-veliki.gpx",
    "thumbnail": "images/thumbnails/vran-veliki.jpg"
  },
  {
    "id": 26,
    "slug": "cvrsnica-hajducka-vrata",
    "name": "Hajdučka Vrata",
    "area": "Čvrsnica",
    "mountain": "Čvrsnica",
    "distanceKm": 15,
    "elevationM": 950,
    "durationH": 7.5,
    "startLat": 43.54,
    "startLon": 17.561,
    "routeType": "Povratna (isti put)",
    "destinations": ["Hajdučka Vrata"],
    "tags": ["Vidikovac", "Široka poljana", "Plato"],
    "description": "Kultno kameno ‘vrata’, zahtjevniji uspon.",
    "gpx": "/gps/cvrsnica-hajducka-vrata.gpx",
    "thumbnail": "images/thumbnails/cvrsnica-hajducka-vrata.jpg"
  },
  {
    "id": 27,
    "slug": "cabulja-vlajna",
    "name": "Čabulja – Velika Vlajna",
    "area": "Čabulja",
    "mountain": "Čabulja",
    "distanceKm": 11.5,
    "elevationM": 780,
    "durationH": 5.5,
    "startLat": 43.43,
    "startLon": 17.71,
    "routeType": "Povratna (isti put)",
    "destinations": ["Velika Vlajna"],
    "tags": ["Mostar", "Kamenjar"],
    "description": "Kamenjar iznad Mostara.",
    "gpx": "/gps/cabulja-vlajna.gpx",
    "thumbnail": "images/thumbnails/cabulja-vlajna.jpg"
  },
  {
    "id": 28,
    "slug": "prenj-zelena-glava",
    "name": "Prenj – Zelena glava",
    "area": "Prenj",
    "mountain": "Prenj",
    "distanceKm": 14,
    "elevationM": 1200,
    "durationH": 8,
    "startLat": 43.52,
    "startLon": 17.94,
    "routeType": "Povratna (isti put)",
    "destinations": ["Zelena glava"],
    "tags": ["Bijele vode", "Tisovica"],
    "description": "Alpski karakter i oštri grebeni.",
    "gpx": "/gps/prenj-zelena-glava.gpx",
    "thumbnail": "images/thumbnails/prenj-zelena-glava.jpg"
  },
  {
    "id": 29,
    "slug": "crvanj-vrh",
    "name": "Crvanj vrh",
    "area": "Crvanj",
    "mountain": "Crvanj",
    "distanceKm": 12,
    "elevationM": 850,
    "durationH": 6,
    "startLat": 43.43,
    "startLon": 18.08,
    "routeType": "Povratna (isti put)",
    "destinations": ["Crvanj"],
    "tags": ["Nevesinje", "Planinski pašnjaci"],
    "description": "Tiša planina s lijepim vizurama.",
    "gpx": "/gps/crvanj-vrh.gpx",
    "thumbnail": "images/thumbnails/crvanj-vrh.jpg"
  },
  {
    "id": 30,
    "slug": "matokit-sv-rok",
    "name": "Matokit – Sveti Rok",
    "area": "Matokit",
    "mountain": "Matokit",
    "distanceKm": 7.8,
    "elevationM": 620,
    "durationH": 3.8,
    "startLat": 43.28,
    "startLon": 17.0,
    "routeType": "Povratna (isti put)",
    "destinations": ["Sveti Rok"],
    "tags": ["Vrgorac", "Strm uspon"],
    "description": "Iznad Vrgorca, kratko i strmo.",
    "gpx": "/gps/matokit-sv-rok.gpx",
    "thumbnail": "images/thumbnails/matokit-sv-rok.jpg"
  },
  {
    "id": 31,
    "slug": "velez-botin",
    "name": "Velež – Botin",
    "area": "Velež",
    "mountain": "Velež",
    "distanceKm": 10.5,
    "elevationM": 850,
    "durationH": 5.5,
    "startLat": 43.31,
    "startLon": 17.99,
    "routeType": "Povratna (isti put)",
    "destinations": ["Botin"],
    "tags": ["Podvelež", "Mostar"],
    "description": "Surovi kamen i snažni pogledi.",
    "gpx": "/gps/velez-botin.gpx",
    "thumbnail": "images/thumbnails/velez-botin.jpg"
  },
  {
    "id": 32,
    "slug": "visocica-vito",
    "name": "Visočica – Vito",
    "area": "Visočica",
    "mountain": "Visočica",
    "distanceKm": 13,
    "elevationM": 900,
    "durationH": 6.5,
    "startLat": 43.67,
    "startLon": 18.09,
    "routeType": "Povratna (isti put)",
    "destinations": ["Vito"],
    "tags": ["Rakitnica", "Grebenska staza"],
    "description": "Greben iznad kanjona Rakitnice.",
    "gpx": "/gps/visocica-vito.gpx",
    "thumbnail": "images/thumbnails/visocica-vito.jpg"
  },
  {
    "id": 33,
    "slug": "bjelasnica-vrh",
    "name": "Bjelašnica vrh",
    "area": "Bjelašnica",
    "mountain": "Bjelašnica",
    "distanceKm": 9.5,
    "elevationM": 700,
    "durationH": 4.5,
    "startLat": 43.71,
    "startLon": 18.26,
    "routeType": "Povratna (isti put)",
    "destinations": ["Bjelašnica"],
    "tags": ["Opservatorij", "Ivan planina"],
    "description": "Otvoreni platoi i vjetar na vrhu.",
    "gpx": "/gps/bjelasnica-vrh.gpx",
    "thumbnail": "images/thumbnails/bjelasnica-vrh.jpg"
  },
  {
    "id": 34,
    "slug": "treskavica-turov",
    "name": "Treskavica – Turov",
    "area": "Treskavica",
    "mountain": "Treskavica",
    "distanceKm": 15.5,
    "elevationM": 1000,
    "durationH": 7.5,
    "startLat": 43.6,
    "startLon": 18.35,
    "routeType": "Povratna (isti put)",
    "destinations": ["Turov"],
    "tags": ["Veliko jezero", "Crno jezero"],
    "description": "Divlja planina s jezerima.",
    "gpx": "/gps/treskavica-turov.gpx",
    "thumbnail": "images/thumbnails/treskavica-turov.jpg"
  },
  {
    "id": 35,
    "slug": "zelengora-orlovacko",
    "name": "Zelengora – Orlovačko jezero",
    "area": "Zelengora",
    "mountain": "Zelengora",
    "distanceKm": 12,
    "elevationM": 500,
    "durationH": 5,
    "startLat": 43.3,
    "startLon": 18.72,
    "routeType": "Kružna",
    "destinations": ["Orlovačko jezero"],
    "tags": ["Sutjeska", "Jezera Zelengore"],
    "description": "Lagani usponi i kristalna jezera.",
    "gpx": "/gps/zelengora-orlovacko.gpx",
    "thumbnail": "images/thumbnails/zelengora-orlovacko.jpg"
  },
  {
    "id": 36,
    "slug": "volujak-greben",
    "name": "Volujak greben",
    "area": "Volujak",
    "mountain": "Volujak",
    "distanceKm": 14.5,
    "elevationM": 1100,
    "durationH": 8,
    "startLat": 43.25,
    "startLon": 18.69,
    "routeType": "Povratna (isti put)",
    "destinations": ["Volujak"],
    "tags": ["Perućica", "Greben"],
    "description": "Dugi grebeni iznad Perućice.",
    "gpx": "/gps/volujak-greben.gpx",
    "thumbnail": "images/thumbnails/volujak-greben.jpg"
  },
  {
    "id": 37,
    "slug": "maglic-bih",
    "name": "Maglić BiH vrh",
    "area": "Maglić",
    "mountain": "Maglić",
    "distanceKm": 13,
    "elevationM": 1200,
    "durationH": 7.5,
    "startLat": 43.31,
    "startLon": 18.74,
    "routeType": "Povratna (isti put)",
    "destinations": ["Maglić"],
    "tags": ["Trnovačko jezero", "Sutjeska NP"],
    "description": "Najviši vrh BiH, krševit teren.",
    "gpx": "/gps/maglic-bih.gpx",
    "thumbnail": "images/thumbnails/maglic-bih.jpg"
  },
  {
    "id": 38,
    "slug": "lelija-velika",
    "name": "Lelija – Velika Lelija",
    "area": "Lelija",
    "mountain": "Lelija",
    "distanceKm": 12.2,
    "elevationM": 820,
    "durationH": 6,
    "startLat": 43.38,
    "startLon": 18.55,
    "routeType": "Povratna (isti put)",
    "destinations": ["Velika Lelija"],
    "tags": ["Prašuma Perućica", "Tisina"],
    "description": "Mirna planina s travnatim vršnim dijelom.",
    "gpx": "/gps/lelija-velika.gpx",
    "thumbnail": "images/thumbnails/lelija-velika.jpg"
  },
  {
    "id": 39,
    "slug": "durmitor-bobotov",
    "name": "Bobotov kuk",
    "area": "Durmitor",
    "mountain": "Durmitor",
    "distanceKm": 11.5,
    "elevationM": 1000,
    "durationH": 6.5,
    "startLat": 43.114,
    "startLon": 19.054,
    "routeType": "Povratna (isti put)",
    "destinations": ["Bobotov kuk"],
    "tags": ["Žabljak", "Škrčka jezera"],
    "description": "Najpoznatiji durmitorski uspon.",
    "gpx": "/gps/durmitor-bobotov.gpx",
    "thumbnail": "images/thumbnails/durmitor-bobotov.jpg"
  },
  {
    "id": 40,
    "slug": "komovi-vasojeviski",
    "name": "Komovi – Vasojevićki",
    "area": "Komovi",
    "mountain": "Komovi",
    "distanceKm": 7,
    "elevationM": 620,
    "durationH": 3.5,
    "startLat": 42.71,
    "startLon": 19.61,
    "routeType": "Povratna (isti put)",
    "destinations": ["Kom Vasojevićki"],
    "tags": ["Planinski dom", "Alpski teren"],
    "description": "Strmiji, ali kratak vršni uspon.",
    "gpx": "/gps/komovi-vasojeviski.gpx",
    "thumbnail": "images/thumbnails/komovi-vasojeviski.jpg"
  },
  {
    "id": 41,
    "slug": "prokletije-jezerce",
    "name": "Maja Jezerce",
    "area": "Prokletije",
    "mountain": "Prokletije",
    "distanceKm": 22,
    "elevationM": 1700,
    "durationH": 11,
    "startLat": 42.441,
    "startLon": 19.812,
    "routeType": "Povratna (isti put)",
    "destinations": ["Maja Jezerce"],
    "tags": ["Theth", "Valbona", "Alpski"],
    "description": "Zahtjevna alpska tura Prokletija.",
    "gpx": "/gps/prokletije-jezerce.gpx",
    "thumbnail": "images/thumbnails/prokletije-jezerce.jpg"
  },
  {
    "id": 42,
    "slug": "sar-titov-vrh",
    "name": "Titov vrh",
    "area": "Šar planina",
    "mountain": "Šar planina",
    "distanceKm": 16,
    "elevationM": 1200,
    "durationH": 8.5,
    "startLat": 42.0,
    "startLon": 20.75,
    "routeType": "Povratna (isti put)",
    "destinations": ["Titov vrh"],
    "tags": ["Koritnik", "Šara"],
    "description": "Dugi uspon do najvišeg vrha Šare.",
    "gpx": "/gps/sar-titov-vrh.gpx",
    "thumbnail": "images/thumbnails/sar-titov-vrh.jpg"
  },
  {
    "id": 43,
    "slug": "pag-sv-vid",
    "name": "Otok Pag – Sveti Vid",
    "area": "Otok Pag",
    "mountain": "Otok Pag",
    "distanceKm": 6.5,
    "elevationM": 220,
    "durationH": 2.5,
    "startLat": 44.5,
    "startLon": 14.99,
    "routeType": "Povratna (isti put)",
    "destinations": ["Sveti Vid"],
    "tags": ["Paški zaljev", "Pag vidikovac"],
    "description": "Kameniti otok i pogled na Paški zaljev.",
    "gpx": "/gps/pag-sv-vid.gpx",
    "thumbnail": "images/thumbnails/pag-sv-vid.jpg"
  },
  {
    "id": 44,
    "slug": "peljesac-sv-ilija",
    "name": "Sveti Ilija",
    "area": "Poluotok Pelješac",
    "mountain": "Poluotok Pelješac",
    "distanceKm": 11.8,
    "elevationM": 900,
    "durationH": 6,
    "startLat": 42.97,
    "startLon": 17.16,
    "routeType": "Povratna (isti put)",
    "destinations": ["Sveti Ilija"],
    "tags": ["Orebić", "Pelješka panorama"],
    "description": "Impresivni vidici na Korčulu i Neretvu.",
    "gpx": "/gps/peljesac-sv-ilija.gpx",
    "thumbnail": "images/thumbnails/peljesac-sv-ilija.jpg"
  },
  {
    "id": 45,
    "slug": "sipovo-janj",
    "name": "Šipovo – Janj",
    "area": "Šipovo",
    "mountain": "Šipovo",
    "distanceKm": 8.8,
    "elevationM": 300,
    "durationH": 3.2,
    "startLat": 44.28,
    "startLon": 17.08,
    "routeType": "Kružna",
    "destinations": ["Janj"],
    "tags": ["Janj rijeka", "Šume Šipova"],
    "description": "Šume i izvori rijeke Janj.",
    "gpx": "/gps/sipovo-janj.gpx",
    "thumbnail": "images/thumbnails/sipovo-janj.jpg"
  },
  {
    "id": 46,
    "slug": "hvar-sv-nikola",
    "name": "Otok Hvar – Sv. Nikola",
    "area": "Otok Hvar",
    "mountain": "Otok Hvar",
    "distanceKm": 10.2,
    "elevationM": 650,
    "durationH": 5,
    "startLat": 43.18,
    "startLon": 16.63,
    "routeType": "Povratna (isti put)",
    "destinations": ["Sveti Nikola"],
    "tags": ["Hvar vrh", "Vidikovac"],
    "description": "Najviši vrh Hvara, miris borova.",
    "gpx": "/gps/hvar-sv-nikola.gpx",
    "thumbnail": "images/thumbnails/hvar-sv-nikola.jpg"
  },
  {
    "id": 47,
    "slug": "brac-vidova-gora",
    "name": "Otok Brač – Vidova gora",
    "area": "Otok Brač",
    "mountain": "Otok Brač",
    "distanceKm": 7.5,
    "elevationM": 420,
    "durationH": 3.2,
    "startLat": 43.3,
    "startLon": 16.65,
    "routeType": "Povratna (isti put)",
    "destinations": ["Vidova gora"],
    "tags": ["Zlatni rat", "Supetar"],
    "description": "Pogled na Zlatni rat i Hvar.",
    "gpx": "/gps/brac-vidova-gora.gpx",
    "thumbnail": "images/thumbnails/brac-vidova-gora.jpg"
  },
  {
    "id": 48,
    "slug": "badnjevice-kanjon",
    "name": "Kanjon Badnjevice staza",
    "area": "Kanjon Badnjevice",
    "mountain": "Kanjon Badnjevice",
    "distanceKm": 6.8,
    "elevationM": 260,
    "durationH": 2.8,
    "startLat": 43.44,
    "startLon": 17.48,
    "routeType": "Kružna",
    "destinations": ["Badnjevice"],
    "tags": ["Kanjon", "Mostina"],
    "description": "Kroz kanjon uz stijene i vodu.",
    "gpx": "/gps/badnjevice-kanjon.gpx",
    "thumbnail": "images/thumbnails/badnjevice-kanjon.jpg"
  },
  {
    "id": 49,
    "slug": "ostrc-vrh",
    "name": "Oštrc vrh",
    "area": "Oštrc",
    "mountain": "Oštrc",
    "distanceKm": 8.4,
    "elevationM": 520,
    "durationH": 3.6,
    "startLat": 45.73,
    "startLon": 15.5,
    "routeType": "Povratna (isti put)",
    "destinations": ["Oštrc"],
    "tags": ["Samoborsko gorje", "Japetić"],
    "description": "Samoborsko gorje – kratko i slatko.",
    "gpx": "/gps/ostrc-vrh.gpx",
    "thumbnail": "images/thumbnails/ostrc-vrh.jpg"
  },
  {
    "id": 50,
    "slug": "prenj-otis",
    "name": "Prenj – Otiš",
    "area": "Prenj",
    "mountain": "Prenj",
    "distanceKm": 15,
    "elevationM": 1200,
    "durationH": 7.5,
    "startLat": 43.55,
    "startLon": 17.92,
    "routeType": "Povratna (isti put)",
    "destinations": ["Otiš"],
    "tags": ["Tisovica", "Zelenica"],
    "description": "Snažan uspon na jedan od markantnih vrhova Prenja.",
    "gpx": "/gps/prenj-otis.gpx",
    "thumbnail": "images/thumbnails/prenj-otis.jpg"
  },
  {
    "id": 51,
    "slug": "ucka-vrh-vojak",
    "name": "Učka – Vojak",
    "area": "Učka",
    "mountain": "Učka",
    "distanceKm": 10.5,
    "elevationM": 700,
    "durationH": 5,
    "startLat": 45.306,
    "startLon": 14.192,
    "routeType": "Povratna (isti put)",
    "destinations": ["Vojak"],
    "tags": ["Kvarner", "Vidikovac"],
    "description": "Uspon na najviši vrh Učke s pogledom na Kvarner.",
    "gpx": "/gps/ucka-vojak.gpx",
    "thumbnail": "images/thumbnails/ucka-vojak.jpg"
  },
  {
    "id": 52,
    "slug": "risnjak-schlosserov-dom",
    "name": "Risnjak – Schlosserov dom",
    "area": "Risnjak",
    "mountain": "Risnjak",
    "distanceKm": 9.2,
    "elevationM": 750,
    "durationH": 4.5,
    "startLat": 45.43,
    "startLon": 14.63,
    "routeType": "Povratna (isti put)",
    "destinations": ["Veliki Risnjak"],
    "tags": ["NP Risnjak", "Dom"],
    "description": "Šumskim putom do doma i vidika na Gorski kotar.",
    "gpx": "/gps/risnjak-dom.gpx",
    "thumbnail": "images/thumbnails/risnjak.jpg"
  },
  {
    "id": 53,
    "slug": "snjeznik-hr-vrh",
    "name": "Snježnik (HR) – vrh",
    "area": "Snježnik (HR)",
    "mountain": "Snježnik",
    "distanceKm": 7.4,
    "elevationM": 520,
    "durationH": 3.5,
    "startLat": 45.44,
    "startLon": 14.59,
    "routeType": "Povratna (isti put)",
    "destinations": ["Snježnik"],
    "tags": ["Gorski kotar"],
    "description": "Kratki alpski ugođaj iznad Gorskog kotara.",
    "gpx": "/gps/snjeznik-hr.gpx",
    "thumbnail": "images/thumbnails/snjeznik-hr.jpg"
  },
  {
    "id": 54,
    "slug": "papuk-ivina-voda",
    "name": "Papuk – Ivina voda krug",
    "area": "Papuk",
    "mountain": "Papuk",
    "distanceKm": 12,
    "elevationM": 450,
    "durationH": 4.5,
    "startLat": 45.51,
    "startLon": 17.66,
    "routeType": "Kružna",
    "destinations": ["Ivina voda"],
    "tags": ["Park prirode", "Šume"],
    "description": "Lagani šumski krug kroz Park prirode Papuk.",
    "gpx": "/gps/papuk-ivina.gpx",
    "thumbnail": "images/thumbnails/papuk.jpg"
  },
  {
    "id": 55,
    "slug": "psunj-brezovo-polje",
    "name": "Psunj – Brezovo Polje",
    "area": "Psunj",
    "mountain": "Psunj",
    "distanceKm": 10,
    "elevationM": 460,
    "durationH": 4,
    "startLat": 45.34,
    "startLon": 17.65,
    "routeType": "Povratna (isti put)",
    "destinations": ["Brezovo Polje"],
    "tags": ["Slavonija", "Šuma"],
    "description": "Najviša točka Psunja kroz guste šume.",
    "gpx": "/gps/psunj-brezovo.gpx",
    "thumbnail": "images/thumbnails/psunj.jpg"
  },
  {
    "id": 56,
    "slug": "kalnik-vranilac",
    "name": "Kalnik – Vranilac",
    "area": "Kalnik",
    "mountain": "Kalnik",
    "distanceKm": 7.2,
    "elevationM": 420,
    "durationH": 3.2,
    "startLat": 46.12,
    "startLon": 16.4,
    "routeType": "Povratna (isti put)",
    "destinations": ["Vranilac"],
    "tags": ["Stijene", "Greben"],
    "description": "Greben Kalnika s kratkim stjenovitim dionicama.",
    "gpx": "/gps/kalnik-vranilac.gpx",
    "thumbnail": "images/thumbnails/kalnik.jpg"
  },
  {
    "id": 57,
    "slug": "ugljan-sv-mihovil",
    "name": "Ugljan – Sv. Mihovil",
    "area": "Ugljan",
    "mountain": "Ugljan",
    "distanceKm": 6.5,
    "elevationM": 220,
    "durationH": 2.5,
    "startLat": 44.08,
    "startLon": 15.12,
    "routeType": "Povratna (isti put)",
    "destinations": ["Sv. Mihovil"],
    "tags": ["Tvrđava", "More"],
    "description": "Lagani uspon do tvrđave s pogledom na Zadar.",
    "gpx": "/gps/ugljan-mihovil.gpx",
    "thumbnail": "images/thumbnails/ugljan.jpg"
  },
  {
    "id": 58,
    "slug": "krk-obzova",
    "name": "Krk – Obzova",
    "area": "Krk",
    "mountain": "Krk",
    "distanceKm": 9,
    "elevationM": 380,
    "durationH": 3.5,
    "startLat": 45.05,
    "startLon": 14.6,
    "routeType": "Povratna (isti put)",
    "destinations": ["Obzova"],
    "tags": ["Kamenjar", "Otok"],
    "description": "Najviši vrh Krka preko kamenjara.",
    "gpx": "/gps/krk-obzova.gpx",
    "thumbnail": "images/thumbnails/krk.jpg"
  },
  {
    "id": 59,
    "slug": "cres-sis",
    "name": "Cres – Sis",
    "area": "Cres",
    "mountain": "Cres",
    "distanceKm": 8.2,
    "elevationM": 420,
    "durationH": 3.5,
    "startLat": 45.06,
    "startLon": 14.41,
    "routeType": "Povratna (isti put)",
    "destinations": ["Sis"],
    "tags": ["Vidikovac", "Otok"],
    "description": "Ćutin pogled na Kvarner i Lubenice.",
    "gpx": "/gps/cres-sis.gpx",
    "thumbnail": "images/thumbnails/cres.jpg"
  },
  {
    "id": 60,
    "slug": "mljet-montokuc",
    "name": "Mljet – Montokuc",
    "area": "Mljet",
    "mountain": "Mljet",
    "distanceKm": 6.8,
    "elevationM": 250,
    "durationH": 2.8,
    "startLat": 42.77,
    "startLon": 17.38,
    "routeType": "Povratna (isti put)",
    "destinations": ["Montokuc"],
    "tags": ["NP Mljet", "Jezera"],
    "description": "Lagano do najvišeg vrha NP Mljet.",
    "gpx": "/gps/mljet-montokuc.gpx",
    "thumbnail": "images/thumbnails/mljet.jpg"
  },
  {
    "id": 61,
    "slug": "nanos-plesa",
    "name": "Nanos – Pleša",
    "area": "Nanos",
    "mountain": "Nanos",
    "distanceKm": 8.5,
    "elevationM": 650,
    "durationH": 4,
    "startLat": 45.77,
    "startLon": 14.05,
    "routeType": "Povratna (isti put)",
    "destinations": ["Pleša"],
    "tags": ["Burja", "Greben"],
    "description": "Vjetroviti grebeni i široki pogledi.",
    "gpx": "/gps/nanos-plesa.gpx",
    "thumbnail": "images/thumbnails/nanos.jpg"
  },
  {
    "id": 62,
    "slug": "sneznik-slo",
    "name": "Snežnik (SLO) – Veliki Snežnik",
    "area": "Snežnik (SLO)",
    "mountain": "Snežnik",
    "distanceKm": 12,
    "elevationM": 720,
    "durationH": 5,
    "startLat": 45.58,
    "startLon": 14.46,
    "routeType": "Povratna (isti put)",
    "destinations": ["Veliki Snežnik"],
    "tags": ["Notranjska", "Dom"],
    "description": "Šumski uspon do doma i vidika.",
    "gpx": "/gps/sneznik-slo.gpx",
    "thumbnail": "images/thumbnails/sneznik-slo.jpg"
  },
  {
    "id": 63,
    "slug": "stol-karavanke",
    "name": "Stol (Karavanke)",
    "area": "Stol (Karavanke)",
    "mountain": "Karavanke",
    "distanceKm": 10.8,
    "elevationM": 1050,
    "durationH": 6,
    "startLat": 46.43,
    "startLon": 14.22,
    "routeType": "Povratna (isti put)",
    "destinations": ["Stol"],
    "tags": ["Karavanke", "Greben"],
    "description": "Oštriji uspon na granici s Austrijom.",
    "gpx": "/gps/stol-karavanke.gpx",
    "thumbnail": "images/thumbnails/stol.jpg"
  },
  {
    "id": 64,
    "slug": "krn-vrh",
    "name": "Krn – vrh",
    "area": "Krn",
    "mountain": "Krn",
    "distanceKm": 11.5,
    "elevationM": 1150,
    "durationH": 6.5,
    "startLat": 46.3,
    "startLon": 13.63,
    "routeType": "Povratna (isti put)",
    "destinations": ["Krn"],
    "tags": ["Soča", "Bovško"],
    "description": "Pogledi na Soču i bojišnice WWI.",
    "gpx": "/gps/krn-vrh.gpx",
    "thumbnail": "images/thumbnails/krn.jpg"
  },
  {
    "id": 65,
    "slug": "grintovec-vrh",
    "name": "Grintovec – vrh",
    "area": "Grintovec",
    "mountain": "Grintovec",
    "distanceKm": 13,
    "elevationM": 1500,
    "durationH": 7.5,
    "startLat": 46.35,
    "startLon": 14.6,
    "routeType": "Povratna (isti put)",
    "destinations": ["Grintovec"],
    "tags": ["Kamniško-Savinjske Alpe"],
    "description": "Najviši vrh KSA, alpski teren.",
    "gpx": "/gps/grintovec.gpx",
    "thumbnail": "images/thumbnails/grintovec.jpg"
  },
  {
    "id": 66,
    "slug": "velika-planina-domovi",
    "name": "Velika planina – domovi",
    "area": "Velika planina",
    "mountain": "Velika planina",
    "distanceKm": 9,
    "elevationM": 450,
    "durationH": 3.5,
    "startLat": 46.31,
    "startLon": 14.63,
    "routeType": "Kružna",
    "destinations": ["Planšarsko naselje"],
    "tags": ["Pastiri", "Kučice"],
    "description": "Šetnja među pastirskim kolibama i vidici.",
    "gpx": "/gps/velika-planina.gpx",
    "thumbnail": "images/thumbnails/velika-planina.jpg"
  },
  {
    "id": 67,
    "slug": "vitosha-cherni-vrah",
    "name": "Vitosha – Cherni Vrah",
    "area": "Vitosha",
    "mountain": "Vitosha",
    "distanceKm": 12,
    "elevationM": 700,
    "durationH": 5,
    "startLat": 42.56,
    "startLon": 23.28,
    "routeType": "Povratna (isti put)",
    "destinations": ["Cherni Vrah"],
    "tags": ["Sofija", "Plato"],
    "description": "Lagani uspon iznad Sofije do najvišeg vrha.",
    "gpx": "/gps/vitosha-cherni.gpx",
    "thumbnail": "images/thumbnails/vitosha.jpg"
  },
  {
    "id": 68,
    "slug": "rila-musala",
    "name": "Rila – Musala",
    "area": "Rila",
    "mountain": "Rila",
    "distanceKm": 14,
    "elevationM": 800,
    "durationH": 6,
    "startLat": 42.18,
    "startLon": 23.58,
    "routeType": "Povratna (isti put)",
    "destinations": ["Musala"],
    "tags": ["Najviši BG", "Jezera"],
    "description": "Najviši vrh Bugarske, žičara + uspon.",
    "gpx": "/gps/rila-musala.gpx",
    "thumbnail": "images/thumbnails/musala.jpg"
  },
  {
    "id": 69,
    "slug": "pirin-vihren",
    "name": "Pirin – Vihren",
    "area": "Pirin",
    "mountain": "Pirin",
    "distanceKm": 9.5,
    "elevationM": 950,
    "durationH": 5.5,
    "startLat": 41.77,
    "startLon": 23.4,
    "routeType": "Povratna (isti put)",
    "destinations": ["Vihren"],
    "tags": ["Mramor", "Alpski"],
    "description": "Stjenovit uspon na mramorni vrh Pirina.",
    "gpx": "/gps/pirin-vihren.gpx",
    "thumbnail": "images/thumbnails/vihren.jpg"
  },
  {
    "id": 70,
    "slug": "balkan-botev",
    "name": "Balkan (Stara planina BG) – Botev",
    "area": "Balkan (Stara planina BG)",
    "mountain": "Stara planina (BG)",
    "distanceKm": 16,
    "elevationM": 1100,
    "durationH": 7,
    "startLat": 42.72,
    "startLon": 24.91,
    "routeType": "Povratna (isti put)",
    "destinations": ["Botev"],
    "tags": ["Vodopadi", "Greben"],
    "description": "Greben do najvišeg vrha centralnog Balkana.",
    "gpx": "/gps/balkan-botev.gpx",
    "thumbnail": "images/thumbnails/botev.jpg"
  },
  {
    "id": 71,
    "slug": "rhodope-snezhanka",
    "name": "Rhodope – Snezhanka",
    "area": "Rhodope",
    "mountain": "Rhodope",
    "distanceKm": 10,
    "elevationM": 500,
    "durationH": 4,
    "startLat": 41.65,
    "startLon": 24.7,
    "routeType": "Kružna",
    "destinations": ["Snezhanka"],
    "tags": ["Šuma", "Kula"],
    "description": "Šetnja do tornja Snezhanka, panorame.",
    "gpx": "/gps/rhodope-snezhanka.gpx",
    "thumbnail": "images/thumbnails/rhodope.jpg"
  },
  {
    "id": 72,
    "slug": "osogovo-ruen",
    "name": "Osogovo – Ruen",
    "area": "Osogovo",
    "mountain": "Osogovo",
    "distanceKm": 18,
    "elevationM": 1000,
    "durationH": 8,
    "startLat": 42.2,
    "startLon": 22.55,
    "routeType": "Povratna (isti put)",
    "destinations": ["Ruen"],
    "tags": ["Granica", "Livade"],
    "description": "Duga tura do najvišeg vrha Osogova.",
    "gpx": "/gps/osogovo-ruen.gpx",
    "thumbnail": "images/thumbnails/osogovo.jpg"
  },
  {
    "id": 73,
    "slug": "belasica-rupite",
    "name": "Belasica – Tumba (trojmeđa)",
    "area": "Belasica",
    "mountain": "Belasica",
    "distanceKm": 12,
    "elevationM": 700,
    "durationH": 5.5,
    "startLat": 41.38,
    "startLon": 23.1,
    "routeType": "Povratna (isti put)",
    "destinations": ["Tumba"],
    "tags": ["Trojmeđa", "Vidikovci"],
    "description": "Vrh na granici BG–MK–GR.",
    "gpx": "/gps/belasica-tumba.gpx",
    "thumbnail": "images/thumbnails/belasica.jpg"
  },
  {
    "id": 74,
    "slug": "strandzha-golyamo-gradishte",
    "name": "Strandzha – Golyamo Gradishte",
    "area": "Strandzha",
    "mountain": "Strandzha",
    "distanceKm": 11,
    "elevationM": 400,
    "durationH": 4,
    "startLat": 42.07,
    "startLon": 27.5,
    "routeType": "Povratna (isti put)",
    "destinations": ["Golyamo Gradishte"],
    "tags": ["Crno more", "Šume"],
    "description": "Meka šumska tura uz more.",
    "gpx": "/gps/strandzha-gradishte.gpx",
    "thumbnail": "images/thumbnails/strandzha.jpg"
  },
  {
    "id": 75,
    "slug": "kopaonik-pancicev-vrh",
    "name": "Kopaonik – Pančićev vrh",
    "area": "Kopaonik",
    "mountain": "Kopaonik",
    "distanceKm": 8,
    "elevationM": 350,
    "durationH": 3,
    "startLat": 43.29,
    "startLon": 20.81,
    "routeType": "Kružna",
    "destinations": ["Pančićev vrh"],
    "tags": ["Ski centar", "Vidik"],
    "description": "Lagani uspon preko skijaških staza.",
    "gpx": "/gps/kopaonik-pancic.gpx",
    "thumbnail": "images/thumbnails/kopaonik.jpg"
  },
  {
    "id": 76,
    "slug": "stara-planina-rs-midzor",
    "name": "Stara planina (RS) – Midžor",
    "area": "Stara planina (RS)",
    "mountain": "Stara planina",
    "distanceKm": 16,
    "elevationM": 900,
    "durationH": 7,
    "startLat": 43.37,
    "startLon": 22.66,
    "routeType": "Povratna (isti put)",
    "destinations": ["Midžor"],
    "tags": ["Granica", "Livade"],
    "description": "Najviši vrh Srbije, dugi greben.",
    "gpx": "/gps/stara-midzor.gpx",
    "thumbnail": "images/thumbnails/midzor.jpg"
  },
  {
    "id": 77,
    "slug": "rtanj-vrh",
    "name": "Rtanj – Šiljak",
    "area": "Rtanj",
    "mountain": "Rtanj",
    "distanceKm": 8.6,
    "elevationM": 900,
    "durationH": 4.5,
    "startLat": 43.75,
    "startLon": 21.9,
    "routeType": "Povratna (isti put)",
    "destinations": ["Šiljak"],
    "tags": ["Piramida", "Panorama"],
    "description": "Strm, ali kratak uspon do Šiljka.",
    "gpx": "/gps/rtanj-siljak.gpx",
    "thumbnail": "images/thumbnails/rtanj.jpg"
  },
  {
    "id": 78,
    "slug": "suva-planina-trem",
    "name": "Suva planina – Trem",
    "area": "Suva planina",
    "mountain": "Suva planina",
    "distanceKm": 15,
    "elevationM": 1100,
    "durationH": 7,
    "startLat": 43.18,
    "startLon": 22.04,
    "routeType": "Povratna (isti put)",
    "destinations": ["Trem"],
    "tags": ["Greben", "Niš"],
    "description": "Oštar greben i dugi vidici.",
    "gpx": "/gps/suva-trem.gpx",
    "thumbnail": "images/thumbnails/suva.jpg"
  },
  {
    "id": 79,
    "slug": "zlatibor-tornik",
    "name": "Zlatibor – Tornik",
    "area": "Zlatibor",
    "mountain": "Zlatibor",
    "distanceKm": 9.5,
    "elevationM": 420,
    "durationH": 3.5,
    "startLat": 43.67,
    "startLon": 19.64,
    "routeType": "Povratna (isti put)",
    "destinations": ["Tornik"],
    "tags": ["Pašnjaci", "Ski"],
    "description": "Valovite livade i šumske ceste.",
    "gpx": "/gps/zlatibor-tornik.gpx",
    "thumbnail": "images/thumbnails/zlatibor.jpg"
  },
  {
    "id": 80,
    "slug": "tara-banjska-stena",
    "name": "Tara – Banjska stena",
    "area": "Tara",
    "mountain": "Tara",
    "distanceKm": 7,
    "elevationM": 260,
    "durationH": 2.5,
    "startLat": 43.94,
    "startLon": 19.39,
    "routeType": "Povratna (isti put)",
    "destinations": ["Banjska stena"],
    "tags": ["Drina", "Vidikovac"],
    "description": "Kratka šetnja do najpoznatijeg vidikovca.",
    "gpx": "/gps/tara-banjska.gpx",
    "thumbnail": "images/thumbnails/tara.jpg"
  },
  {
    "id": 81,
    "slug": "fruska-gora-crveni-cot",
    "name": "Fruška gora – Crveni Čot",
    "area": "Fruška gora",
    "mountain": "Fruška gora",
    "distanceKm": 12.5,
    "elevationM": 450,
    "durationH": 4.5,
    "startLat": 45.15,
    "startLon": 19.72,
    "routeType": "Kružna",
    "destinations": ["Crveni Čot"],
    "tags": ["Manastiri", "Vojvodina"],
    "description": "Blaži usponi kroz šumu i vinograde.",
    "gpx": "/gps/fruska-cot.gpx",
    "thumbnail": "images/thumbnails/fruska.jpg"
  },
  {
    "id": 82,
    "slug": "rudnik-ostr-vrh",
    "name": "Rudnik – Ostrvica",
    "area": "Rudnik",
    "mountain": "Rudnik",
    "distanceKm": 6.4,
    "elevationM": 380,
    "durationH": 2.5,
    "startLat": 44.1,
    "startLon": 20.47,
    "routeType": "Povratna (isti put)",
    "destinations": ["Ostrvica"],
    "tags": ["Stijene", "Vidik"],
    "description": "Kratko i strmo na kameni vrh.",
    "gpx": "/gps/rudnik-ostrvica.gpx",
    "thumbnail": "images/thumbnails/rudnik.jpg"
  },
  {
    "id": 83,
    "slug": "jastrebac-jezero",
    "name": "Jastrebac – jezera",
    "area": "Jastrebac",
    "mountain": "Jastrebac",
    "distanceKm": 8.8,
    "elevationM": 350,
    "durationH": 3.2,
    "startLat": 43.28,
    "startLon": 21.24,
    "routeType": "Kružna",
    "destinations": ["Jezero"],
    "tags": ["Šuma", "Kružna"],
    "description": "Lagani krug oko šumskih jezera.",
    "gpx": "/gps/jastrebac-jezera.gpx",
    "thumbnail": "images/thumbnails/jastrebac.jpg"
  },
  {
    "id": 84,
    "slug": "maljen-divcibare-paljba",
    "name": "Maljen (Divčibare) – Paljba",
    "area": "Maljen (Divčibare)",
    "mountain": "Maljen",
    "distanceKm": 7.5,
    "elevationM": 300,
    "durationH": 3,
    "startLat": 44.11,
    "startLon": 19.99,
    "routeType": "Povratna (isti put)",
    "destinations": ["Paljba"],
    "tags": ["Divčibare", "Vidikovac"],
    "description": "Porodična tura do vidikovca Paljba.",
    "gpx": "/gps/maljen-paljba.gpx",
    "thumbnail": "images/thumbnails/maljen.jpg"
  },
  {
    "id": 85,
    "slug": "homolje-kucaj",
    "name": "Homolje – vršni greben",
    "area": "Homolje",
    "mountain": "Homoljske planine",
    "distanceKm": 14,
    "elevationM": 650,
    "durationH": 6,
    "startLat": 44.32,
    "startLon": 21.7,
    "routeType": "Kružna",
    "destinations": ["Greben"],
    "tags": ["Pejzaži", "Krš"],
    "description": "Krševiti greben i pastirski pašnjaci.",
    "gpx": "/gps/homolje-greben.gpx",
    "thumbnail": "images/thumbnails/homolje.jpg"
  },
  {
    "id": 86,
    "slug": "orjen-subra",
    "name": "Orjen – Subra",
    "area": "Orjen",
    "mountain": "Orjen",
    "distanceKm": 9.8,
    "elevationM": 900,
    "durationH": 5.5,
    "startLat": 42.58,
    "startLon": 18.6,
    "routeType": "Povratna (isti put)",
    "destinations": ["Subra"],
    "tags": ["Krš", "Kotori"],
    "description": "Impresivni krški zidovi i pogledi.",
    "gpx": "/gps/orjen-subra.gpx",
    "thumbnail": "images/thumbnails/orjen.jpg"
  },
  {
    "id": 87,
    "slug": "lovcen-jezerski-vrh",
    "name": "Lovćen – Jezerski vrh",
    "area": "Lovćen",
    "mountain": "Lovćen",
    "distanceKm": 6.5,
    "elevationM": 350,
    "durationH": 2.5,
    "startLat": 42.4,
    "startLon": 18.82,
    "routeType": "Povratna (isti put)",
    "destinations": ["Mauzolej"],
    "tags": ["Njegoš", "Panorama"],
    "description": "Stepenice do mauzoleja i vidikovca.",
    "gpx": "/gps/lovcen-jezerski.gpx",
    "thumbnail": "images/thumbnails/lovcen.jpg"
  },
  {
    "id": 88,
    "slug": "rumija-vrh",
    "name": "Rumija – vrh",
    "area": "Rumija",
    "mountain": "Rumija",
    "distanceKm": 11,
    "elevationM": 950,
    "durationH": 5.5,
    "startLat": 42.09,
    "startLon": 19.19,
    "routeType": "Povratna (isti put)",
    "destinations": ["Rumija"],
    "tags": ["Bar", "More"],
    "description": "Uspon iznad Bara s pogledima na Jadran.",
    "gpx": "/gps/rumija.gpx",
    "thumbnail": "images/thumbnails/rumija.jpg"
  }
    
  ];
