  const TRAILS = [
    
  {
    "id": 1,
    "slug": "hiking-trail-barzonja-jelinak-cvrsnica-mountain-bosnia-and-herzegovina",
    "name": "Vrh Jelinak (Čvrsnica)",
    "area": "Čvrsnica",
    "mountain": "Čvrsnica",
    "distanceKm": 5.5,
    "elevationM": 570,
    "durationH": 4.5,
    "startLat": 43.59084,
    "startLon": 17.47495,
    "routeType": "Povratna (isti put)",
    "destinations": ["Čvrsnica"],
    "tags": ["Čvrsnica", "Jelinak", "Park prirode Blidinje", "Blidinje", "Barzonja"],
    "description": "Uspon na Jelinak s Barzonje. Planinarenje grebenom s prelijepim vidicima na Blidinjsko Jezero, Vran Planinu i više predjele Čvrsnice. Greben Jelinka je ujedno i najljepši vidikovac na Blidinjsko jezero kojeg će te pronaći u Parku prirode Blidinje.",
    "thumbnail": "images/hiking-trail-jelinak-cvrsnica-blidinje-nature-park-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza na vrh Jelinak u Parku prirode Blidinje s lijepim pogledom na Blidinjsko jezero."
  },
  {
    "id": 2,
    "slug": "hiking-trail-hajducka-vrata-cvrsnica-mountain-bosnia-and-herzegovina",
    "name": "Hajdučka Vrata (najlakša staza)",
    "area": "Čvrsnica",
    "mountain": "Čvrsnica",
    "distanceKm": 16.5,
    "elevationM": 700,
    "durationH": 7,
    "startLat": 43.67306,
    "startLon": 17.62273,
    "routeType": "Povratna (isti put)",
    "destinations": ["Hajdučka Vrata"],
    "tags": ["Planinarski dom Vilinac", "Hajdučka Vrata", "Zaglavlje", "Vitlenica", "Park Prirode Blidinje", "Trinjača", "Via Dinarica", "Čvrsnica"],
    "description": "Uspon do Hajdučkih Vrata najljepšom planinarskom stazom i pogled iza Vrata na kanjon dubok 1800m. Ova staza pri povratku ostavlja dojam kao da hodate nekom drugom zbog raznolikog planinskog pejzaža Čvrsnice.",
    "thumbnail": "images/hiking-trail-hajducka-vrata-cvrsnica-blidinje-nature-park-bosnia-and-herzegovina.jpg",
    "alt": "Najpopularnija planinarska staza na Balkanu do Hajdučkih Vrata u srcu Hercegovine. Najljepše planinarske staze u Bosni i Hercegovini."
  },
  {
    "id": 3,
    "slug": "hiking-trail-rujiste-zelena-glava-prenj-mountain-bosnia-and-herzegovina",
    "name": "Zelena Glava s Rujišta (Prenj)",
    "area": "Prenj",
    "mountain": "Prenj",
    "distanceKm": 27,
    "elevationM": 1450,
    "durationH": 11,
    "startLat": 43.46480,
    "startLon": 17.96286,
    "routeType": "Povratna (isti put)",
    "destinations": ["Prenj"],
    "tags": ["Prenj", "Zelena Glava", "Bijele Vode", "Jezerce", "Rujište", "Mostar", "Adnan Krilić"],
    "description": "Uspon na Zelenu Glavu s Rujišta. Dugotrajna staza koja prolazi lijepom dolinom u srcu Prenj planine. Zadnji koraci osigurani sajlom. Pogled s najvišeg vrha se prostire do svih prenjskih 2000-njaka. Mogućnost spavanja u Pl. domu Adnan Krilić i u Pl. skloništu Jezerce.",
    "thumbnail": "images/hiking-trail-zelena-glava-prenj-mountain-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza s Rujišta na Zelenu Glavu na Prenj planini koja je prava atrakcija u blizini Mostara."
  },
  {
    "id": 4,
    "slug": "hiking-trail-gornja-brela-pakline-biokovo-mountain-croatia",
    "name": "Pakline preko Šuplje Stine (Biokovo)",
    "area": "Biokovo",
    "mountain": "Biokovo",
    "distanceKm": 7,
    "elevationM": 480,
    "durationH": 4.5,
    "startLat": 43.38756,
    "startLon": 16.92941,
    "routeType": "Kružna",
    "destinations": ["Biokovo"],
    "tags": ["Biokovo", "Pakline", "Šuplja Stina", "Nevistina Stina", "Gornja Brela", "Biokovo Nature Park"],
    "description": "Jedna od najljepših planinarskih staza u Hrvatskoj. Svaki korak donosi nešto novo. Sklonište na Paklinama s pogledom na more kao iz snova.",
    "thumbnail": "images/hiking-trail-biokovo-mountain-gornja-brela-pakline-croatia.jpg",
    "alt": "Najljepša planinarska staza na Biokovu te u Dalmaciji koja vodi na Pakline s pogledom na more i litice s druge strane. Najljepše planinarske staze u Hrvatskoj."
  },
  {
    "id": 5,
    "slug": "hiking-trail-podgradina-konj-kamesnica-mountain-bosnia-and-herzegovina",
    "name": "Podgradina - Konj (Kamešnica)",
    "area": "Kamešnica",
    "mountain": "Kamešnica",
    "distanceKm": 12.3,
    "elevationM": 1050,
    "durationH": 7.5,
    "startLat": 43.70852,
    "startLon": 16.96295,
    "routeType": "Povratna (isti put)",
    "destinations": ["Kamešnica"],
    "tags": ["Kamešnica", "Konj", "Pešino Vrilo", "Livno", "Buško Jezero", "Livanjsko Polje", "Podgradina"],
    "description": "Uspon na Konja. Staza koja vodi uz žubor potoka. Planinarsko sklonište i izvor, bukova šuma i neodoljiv vidikovac. Šetnja grebenom do vrha.",
    "thumbnail": "images/hiking-trail-kamesnica-mountain-podgradina-konj-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza Podgradina - Konj na planini Kamešnici. Atrakcija u okolici Livna."
  },
  {
    "id": 6,
    "slug": "hiking-trail-blidinje-veliki-vran-vran-mountain-bosnia-and-herzegovina",
    "name": "Hajdučke Vrleti - Veliki Vran",
    "area": "Vran",
    "mountain": "Vran",
    "distanceKm": 8,
    "elevationM": 840,
    "durationH": 5,
    "startLat": 43.65428,
    "startLon": 17.52940,
    "routeType": "Povratna (isti put)",
    "destinations": ["Vran"],
    "tags": ["Vran planina", "Veliki Vran", "Hajdučke Vrleti", "Hajdučko Vrilo", "Blidinje"],
    "description": "Planinarska staza koja vodi dijelom kroz borovu šumu a zatim po travnatim pašnjacima do najvišeg vrha Vran planine. Polazna točka u blizini poznatog restorana u Parku prirode Blidinje.",
    "thumbnail": "images/hiking-trail-vran-mountain-hajducke-vrleti-veliki-vran-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza do najvišeg vrha Vran Planine. Polazna točka pored popularnog restorana Hajdučke Vrleti u srcu Parka prirode Blidinje."
  },
  {
    "id": 7,
    "slug": "hiking-trail-glavas-sinjal-dinara-mountain-croatia-vrh-hrvatske",
    "name": "Vrh Hrvatske iz Glavaša (Dinara)",
    "area": "Dinara",
    "mountain": "Dinara",
    "distanceKm": 17.7,
    "elevationM": 1380,
    "durationH": 9,
    "startLat": 44.01117,
    "startLon": 16.41941,
    "routeType": "Povratna (isti put)",
    "destinations": ["Dinara"],
    "tags": ["Najviši vrh RH", "Glavaš", "Martinova košara", "Dinara", "Sinjal", "Sklonište Drago Grubać"],
    "description": "Najviši vrh RH sa skloništem i lijepim pogledom. Staza koja polazi blizu izvora rijeke Cetine i preko travnatih strmina vodi grebenom Dinare. Na stazi su srednjovjekovna utvrda i planinarsko sklonište.",
    "thumbnail": "images/hiking-trail-dinara-mountain-glavas-vrh-hrvatske-croatia.jpg",
    "alt": "Planinarska staza na planini Dinari koja pored jedne srednjovjekovne utvrde i planinarskog skloništa vodi na najviši vrh Hrvatske."
  },
  {
    "id": 8,
    "slug": "hiking-trail-prisoje-vitrenik-tusnica-mountain-bosnia-and-herzegovina",
    "name": "Prisoje - Vitrenik (Tušnica)",
    "area": "Tušnica",
    "mountain": "Tušnica",
    "distanceKm": 13,
    "elevationM": 960,
    "durationH": 6,
    "startLat": 43.69434,
    "startLon": 17.08365,
    "routeType": "Kružna",
    "destinations": ["Tušnica"],
    "tags": ["Prisoje", "Dobrijevac", "Vitrenik", "Tušnica", "Buško jezero", "Livno", "Tomislavgrad"],
    "description": "Uspon na najviši vrh Tušnice, Vitrenik. Staza koja polazi iz Prisoja vodi do najvišeg vrha pored planinarskog doma Dobrijevac te prelijepim grebenom sve do najvišeg vrha Vitrenik (1697m). Pogled na Buško jezero cijelo vrijeme oduzima dah.",
    "thumbnail": "images/hiking-trail-tusnica-mountain-prisoje-vitrenik-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza na Vitrenik, planina Tušnica. Staza koja polazi iz Prisoja i vrluda travnatim grebenom planine."
  },
  {
    "id": 9,
    "slug": "hiking-trail-satorsko-jezero-veliki-sator-sator-mountain-bosnia-and-herzegovina",
    "name": "Planina Šator (Jezero i vrh)",
    "area": "Šator",
    "mountain": "Šator",
    "distanceKm": 4.9,
    "elevationM": 380,
    "durationH": 3.5,
    "startLat": 44.16747,
    "startLon": 16.60200,
    "routeType": "Povratna (isti put)",
    "destinations": ["Šator"],
    "tags": ["Šator planina", "Šatorsko Jezero", "Bosansko Grahovo"],
    "description": "Obilazak Šatorskog jezera i uspon do najvišeg vrha ove planine uz prelijepe vidikovce na veliko jezero. Pristupni put je makadamski.",
    "thumbnail": "images/hiking-trail-sator-mountain-satorsko-jezero-veliki-sator-bosnia-and-herzegovina.jpg",
    "alt": "Šatorsko jezero i najviši vrh Šatora na prelijepoj planinarskoj stazi"
  },
  {
    "id": 10,
    "slug": "hiking-trail-prijevor-maglic-trnovacko-jezero-maglic-mountain-bosnia-and-herzegovina",
    "name": "Prijevor - Maglić - Trnovačko jezero",
    "area": "Maglić",
    "mountain": "Maglić",
    "distanceKm": 13.5,
    "elevationM": 1200,
    "durationH": 7.5,
    "startLat": 43.28775,
    "startLon": 18.71666,
    "routeType": "Kružna",
    "destinations": ["Maglić"],
    "tags": ["Maglić", "Prijevor", "Sutjeska", "Trnovačko Jezero", "Tara", "Prašuma Perućica", "Vodopad Skakavac", "Tjentište"],
    "description": "Planinarska staza koja pri usponu ima i sajle za dodatno osiguranje. Najviši vrh BiH i pogled s njega na visoke crnogorske planine. Travnata prostranstva i Trnovačko jezero kao najljepši biser Balkana.",
    "thumbnail": "images/hiking-trail-maglic-mountain-prijevor-maglic-trnovacko-jezero-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza s Prijevora na Maglić. Kružna tura uz obilazak Trnovačkog jezera."
  },
  {
    "id": 11,
    "slug": "hiking-trail-vrgorac-sveti-rok-matokit-mountain-bosnia-and-herzegovina",
    "name": "Vrgorac - Sv. Rok (Matokit)",
    "area": "Matokit",
    "mountain": "Matokit",
    "distanceKm": 7.5,
    "elevationM": 790,
    "durationH": 5,
    "startLat": 43.20696,
    "startLon": 17.36823,
    "routeType": "Povratna (isti put)",
    "destinations": ["Matokit"],
    "tags": ["Matokit", "Sveti Rok", "Vrgorac"],
    "description": "Tipična dalmatinska planinarska staza preko kamenjara do na vrh. Staza polazi iz grada Vrgorca i vodi na najviši vrh Matokita, Sveti Rok.",
    "thumbnail": "images/hiking-trail-matokit-mountain-vrgorac-sveti-rok-croatia.jpg",
    "alt": "Planinarska staza Vrgorac - Sveti Rok. Matokit planina."
  },
  {
    "id": 12,
    "slug": "hiking-trail-kruzi-cincar-cincar-mountain-bosnia-and-herzegovina",
    "name": "Pl. dom Kruzi - Cincar",
    "area": "Cincar",
    "mountain": "Cincar",
    "distanceKm": 11.5,
    "elevationM": 780,
    "durationH": 6,
    "startLat": 43.87353,
    "startLon": 17.02449,
    "routeType": "Povratna (isti put)",
    "destinations": ["Cincar"],
    "tags": ["Cincar", "Livno", "Planinarski dom Kruzi", "Izvor Duman", "Divlji konji livno"],
    "description": "Jedinstvena planinarska staza koja od Planinarskog doma Kruzi vodi na najviši vrh Cincara. Staza vodi po visoravni gdje se prolazi pored mnogo krda divljih konja.",
    "thumbnail": "images/hiking-trail-cincar-mountain-kruzi-cincar-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza Kruzi - Cincar. Posjeta divljim konjima na visoravni dok hodate gotovo uvijek moguća."
  },
  {
    "id": 13,
    "slug": "hiking-trail-zahum-idovac-radusa-mountain-bosnia-and-herzegovina",
    "name": "Zahum - Idovac (Raduša)",
    "area": "Raduša",
    "mountain": "Raduša",
    "distanceKm": 13,
    "elevationM": 810,
    "durationH": 6,
    "startLat": 43.83112,
    "startLon": 17.44995,
    "routeType": "Povratna (isti put)",
    "destinations": ["Raduša"],
    "tags": ["Raduša", "Zahum", "Felix staza", "Idovac", "Idovačko jezero", "Rama", "Ramsko jezero", "Diva Grabovčeva"],
    "description": "Planinarska staza na najviši vrh Raduše ispod kojeg se nalazi i istoimeno jezero. Blizu polazne točke se nalazi vidikovac na Ramsko jezero koji svakako vrijedi posjetiti.",
    "thumbnail": "images/hiking-trail-radusa-mountain-zahum-idovac-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza Zahum - Idovac na planini Raduši. Vidikovac na Ramsko jezero u blizini."
  },
  {
    "id": 14,
    "slug": "hiking-trail-radovina-nadkrstac-vranica-mountain-bosnia-and-herzegovina",
    "name": "Radovina - Ločika - Nadkrstac (Vranica)",
    "area": "Vranica",
    "mountain": "Vranica",
    "distanceKm": 13.5,
    "elevationM": 860,
    "durationH": 7,
    "startLat": 43.93813,
    "startLon": 17.70060,
    "routeType": "Kružna",
    "destinations": ["Vranica"],
    "tags": ["Radovina", "Uskoplje", "Ločika", "Krstac", "Nadkrstac", "Vranica", "Prokoško jezero"],
    "description": "Lijepa kružna tura po najvišim obroncima planine Vranice. Od Planinarskog doma Radovina, preko Ločike do najvišeg vrha Nadkrstac. Mnogo izvora i lijep vidikovac na Prokoško jezero.",
    "thumbnail": "images/hiking-trail-vranica-mountain-radovina-locika-nadkrstac-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza Radovina - Ločika - Nadkrstac s vidikovcem na Prokoško jezero."  
  },
  {
    "id": 15,
    "slug": "hiking-trail-kanjon-badnjevice-imotski-croatia",
    "name": "Kanjon Badnjevice",
    "area": "Kanjon Badnjevice",
    "mountain": "Kanjon Badnjevice",
    "distanceKm": 7.5,
    "elevationM": 500,
    "durationH": 4.5,
    "startLat": 43.46956,
    "startLon": 17.16078,
    "routeType": "Kružna",
    "destinations": ["Kanjon Badnjevice"],
    "tags": ["Imotska Krajina", "Turska Kula", "Proložac", "Imotski", "Kanjon Badnjevice", "Ričice", "Bumbari i komarci", "Suvaja"],
    "description": "Lijepa kružna staza koja vodi cijelim kanjonom Badnjevice blizu Imotskog. Prolazak kroz staru tursku kulu i hodanje po rubu litica daju jedinstven doživljaj.",
    "thumbnail": "images/hiking-trail-kanjon-badnjevice-imotski-croatia.jpg",
    "alt": "Planinarska staza kroz Kanjon Badnjevice u blizini Imotskog."
  },
  {
    "id": 16,
    "slug": "hiking-trail-mocila-kolakovac-zavelim-mountain-bosnia-and-herzegovina",
    "name": "Močila - Kolakovac (Zavelim)",
    "area": "Zavelim",
    "mountain": "Zavelim",
    "distanceKm": 7.7,
    "elevationM": 430,
    "durationH": 5,
    "startLat": 43.56794,
    "startLon": 17.13225,
    "routeType": "Kružna",
    "destinations": ["Zavelim"],
    "tags": ["Zavelim", "Močila", "Zagorje", "Roško Polje", "Kolakovac"],
    "description": "Kružna planinarska staza koja od Močila vodi do na najviši vrh Zavelima, Kolakovac. Postoji vrelo na polaznoj točki. Široki pogledi sa vrha na sve strane.",
    "thumbnail": "images/hiking-trail-zavelim-mountain-mocila-kolakovac-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza Močila - Kolakovac na Zavelim planini."
  },
  {
    "id": 17,
    "slug": "hiking-trail-tribistovo-ostrc-ostrc-mountain-bosnia-and-herzegovina",
    "name": "Tribistovo - Šimića pećina - Ružićki potok - Oštrc",
    "area": "Oštrc",
    "mountain": "Oštrc",
    "distanceKm": 12.5,
    "elevationM": 520,
    "durationH": 6,
    "startLat": 43.52137,
    "startLon": 17.34813,
    "routeType": "Povratna (isti put)",
    "destinations": ["Oštrc"],
    "tags": ["Tribistovo", "Tribistovsko jezero", "Šimića pećina", "Vučipolje", "Ružićki potok", "Oštrc"],
    "description": "Staza koja vodi od velikog Tribistovskog jezera do na vrh Oštrca. prolazi pored Šimića pećine te vrluda duž Ružićkog potoka kojeg krase mnogi mali vodopadi.",
    "thumbnail": "images/hiking-trail-ostrc-mountain-tribistovo-simica-pecina-ruzicki-potok-ostrc-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza Tribistovsko jezero - Šimića pećina - Ružićki potok - Veliki Oštrc."
  },
  {
    "id": 18,
    "slug": "hiking-trail-milici-sveti-jure-biokovo-mountain-croatia",
    "name": "Sv. Jure iz Milića (Biokovo)",
    "area": "Biokovo",
    "mountain": "Biokovo",
    "distanceKm": 10.5,
    "elevationM": 1250,
    "durationH": 8,
    "startLat": 43.37481,
    "startLon": 17.07186,
    "routeType": "Povratna (isti put)",
    "destinations": ["Biokovo"],
    "tags": ["Biokovo", "Milići", "Zagvozd", "Sveti Jure", "Repetitor"],
    "description": "Jako strma staza do najvišeg vrha Biokova iz sela Milići. Pogledi sa vrha na more i otoke a s druge strane na dalmatinsku zagoru i hercegovačke planine.",
    "thumbnail": "images/hiking-trail-biokovo-mountain-milici-sveti-jure-croatia.jpg",
    "alt": "Planinarska staza Milići - Sveti Jure na Biokovu."
  },
  {
    "id": 19,
    "slug": "hiking-trail-dragan-selo-skloniste-kada-prenj-mountain-bosnia-and-herzegovina",
    "name": "Dragan Selo - Pl. sklonište Kada (Prenj)",
    "area": "Prenj",
    "mountain": "Prenj",
    "distanceKm": 13,
    "elevationM": 850,
    "durationH": 6.5,
    "startLat": 43.64503,
    "startLon":17.80228,
    "routeType": "Povratna (isti put)",
    "destinations": ["Prenj"],
    "tags": ["Dragan Selo", "Prenj", "Glogošnica", "Dževlanuša", "Podsubaša", "Cetina", "Velevijevac", "Izgorjela Gruda", "Sklonište Kada", "Jablanica"],
    "description": "Jedna od najlakših a ujedno i najljepših staza na Prenju. Polazi iz Dragan Sela te uz Draganjsku Rijeku izlazi do vrha Velevijevac s kojeg se lijepo vide litice Cetine i Izgorjele Grude. Pl. sklonište Kada na najljepšoj mogućoj lokaciji.",
    "thumbnail": "images/hiking-trail-prenj-mountain-dragan-selo-skloniste-kada-bosnia-and-herzegovina.jpg",
    "alt": "Najljepša planinarska staza u Bosni i Hercegovini koja iz Dragan Sela vodi do skloništa Kada na Prenj planini."
  },
  {
    "id": 20,
    "slug": "hiking-trail-masna-luka-plocno-cvrsnica-mountain-bosnia-and-herzegovina",
    "name": "Masna Luka - Pločno (Čvrsnica)",
    "area": "Čvrsnica",
    "mountain": "Čvrsnica",
    "distanceKm": 17,
    "elevationM": 1200,
    "durationH": 9,
    "startLat": 43.63206,
    "startLon": 17.54085,
    "routeType": "Povratna (isti put)",
    "destinations": ["Čvrsnica"],
    "tags": ["Masna Luka", "Pločno", "Ivica Plazonić", "Čvrsnica", "Blidinje", "Park prirode Blidinje", "Ćužića Kuk"],
    "description": "Planinarska staza do najvišeg vrha Čvrsnice koja polazi iz Masne Luke pokraj Pl. doma Masna Luka. Sa svojih 2228m, ovaj vrh je teže osvojiti. Posljednjih 500m je strmi sipar podno visokih litica.",
    "thumbnail": "images/hiking-trail-cvrsnica-mountain-masna-luka-plocno-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja vodi iz Masne Luke na Pločno. Sklad divne prirode u Parku prirode Blidinje."
  },
  {
    "id": 21,
    "slug": "hiking-trail-orlove-stine-bat-svilaja-mountain-croatia",
    "name": "Orlove Stine - Bat (Svilaja)",
    "area": "Svilaja",
    "mountain": "Svilaja",
    "distanceKm": 13,
    "elevationM": 520,
    "durationH": 5,
    "startLat": 43.76946,
    "startLon": 16.52417,
    "routeType": "Kružna",
    "destinations": ["Svilaja"],
    "tags": ["Svilaja", "Orlove Stine", "Bat", "Sinj", "Peručko jezero"],
    "description": "Od Pl. doma Orlove Stine do na najviši vrh vas vodi dobro markirana planinarska staza koja nije posebno teška. S vrha lijepi pogledi na Dinaru, Kamešnicu i Peručko jezero te Petrovo Polje i Mosor. Opcija kružnog povratka je najbolja.",
    "thumbnail": "images/hiking-trail-svilaja-mountain-orlove-stine-bat-croatia.jpg",
    "alt": "Planinarska staza na najviši vrh planine Svilaje. Sinjska okolica i najbliže planine te Peručko jezero kao na dlanu."
  },
  {
    "id": 22,
    "slug": "hiking-trail-life-on-mars-pag-island-croatia",
    "name": "Life on Mars staza (Otok Pag)",
    "area": "Otok Pag",
    "mountain": "Otok Pag",
    "distanceKm": 18,
    "elevationM": 550,
    "durationH": 7.5,
    "startLat": 44.50157,
    "startLon": 15.02153,
    "routeType": "Kružna",
    "destinations": ["Otok Pag"],
    "tags": ["Metajna", "Otok Pag", "Life on Mars trail"],
    "description": "Jedinstvena planinarska staza koja je spojila ugodnu šetnju, zanimljiv pustinjski krajolik otoka Paga, neodoljive poglede na Velebit te najljepše uvale i plaže je upravo Life on Mars trail. Postoji i opcija za Via Ferratu a tu je i visoka stijena za penjanje.",
    "thumbnail": "images/hiking-trail-pag-island-life-on-mars-trail-croatia.jpg",
    "alt": "Jedinstvena planinarska staza Life on Mars Trail na Otoku Pagu."
  },
  {
    "id": 23,
    "slug": "hiking-trail-umberto-girometta-veliki-kabal-vickov-stup-mosor-mountain-croatia",
    "name": "Pl. dom Umberto Girometta - Veliki Kabal - Vickov Stup (Mosor)",
    "area": "Mosor",
    "mountain": "Mosor",
    "distanceKm": 11,
    "elevationM": 770,
    "durationH": 6.5,
    "startLat": 43.51996,
    "startLon": 16.60342,
    "routeType": "Kružna",
    "destinations": ["Mosor"],
    "tags": ["Umberto Girometta", "Veliki Kabal", "Vickov Stup", "Ljubirna", "Mosor", "Sitno Gornje"],
    "description": "Kružna staza po Mosoru, krševit teren i lijepi vidici cijelo vrijeme na grebenu. Odmor pored Planinarskog doma Umberto Girometta je nezaobilazan. Pogledi na Jadransko more očaravaju.",
    "thumbnail": "images/hiking-trail-mosor-mountain-umberto-girometta-veliki-kabal-vickov-stup-croatia.jpg",
    "alt": "Planinarska staza iznad Splita u Dalmaciji. Kružna tura po Mosoru od Planinarskog doma Umberto Girometta do na Veliki Kabal i Vickov Stup."
  },
  {
    "id": 24,
    "slug": "hiking-trail-kokorina-botin-velez-mountain-bosnia-and-herzegovina",
    "name": "Botin iz Kokorine (Velež)",
    "area": "Velež",
    "mountain": "Velež",
    "distanceKm": 20,
    "elevationM": 1050,
    "durationH": 8,
    "startLat": 43.27072,
    "startLon": 17.99113,
    "routeType": "Povratna (isti put)",
    "destinations": ["Velež"],
    "tags": ["Velež", "Kokorina", "Podveležje", "Mostar", "Botin", "Srce Veleža"],
    "description": "Planinarska staza koja vodi na najviši vrh Veleža. Bukova šuma, kamena prostranstva, duboke rupe i visoke litice spojene u jedinstvenu stazu blizu Mostara. Postoji i opcija za skraćenu verziju ako se džipom prijeđe dosta loš makadam kojeg ima više kilometara.",
    "thumbnail": "images/hiking-trail-velez-mountain-kokorina-botin-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza u blizini Mostara na planini Velež. Lijepa staza raznolikih krajobraza koja vodi na najviši vrh Botin."
  },
  {
    "id": 25,
    "slug": "hiking-trail-risovac-veliki-vilinac-cvrsnica-mountain-bosnia-and-herzegovina",
    "name": "Veliki Vilinac Ćurdinom stazom (Čvrsnica)",
    "area": "Čvrsnica",
    "mountain": "Čvrsnica",
    "distanceKm": 14.5,
    "elevationM": 1150,
    "durationH": 8,
    "startLat": 43.65857,
    "startLon": 17.57529,
    "routeType": "Povratna (isti put)",
    "destinations": ["Čvrsnica"],
    "tags": ["Risovac", "Blidinje", "Veliki Vilinac", "Park prirode Blidinje", "Ćurdina staza", "Mali Vilinac", "Čvrsnica", "Krš"],
    "description": "Manje poznata staza koja pored nove Crkve na Risovcu vodi na Mali i Veliki Vilinac. Na ovoj stazi su mnoge opcije za uraditi lijepu kružnu turu jer se siječe s drugim markiranim stazama.",
    "thumbnail": "images/hiking-trail-cvrsnica-mountain-risovac-veliki-vilinac-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza za Veliki Vilinac na planini Čvrsnici koja vodi Ćurdinom stazom."
  },
  {
    "id": 26,
    "slug": "hiking-trail-omrcenica-mali-vran-vran-mountain-bosnia-and-herzegovina",
    "name": "Omrčenica - Mali Vran (Vran)",
    "area": "Vran",
    "mountain": "Vran",
    "distanceKm": 7.5,
    "elevationM": 630,
    "durationH": 6,
    "startLat": 43.64874,
    "startLon": 17.41575,
    "routeType": "Povratna (isti put)",
    "destinations": ["Vran"],
    "tags": ["Vran", "Omrčenica", "Mali Vran", "Mijatova pećina", "Tomislavgrad"],
    "description": "Visoka borova šuma uz maleno vikend naselje na Omrčenici je ujedno i polazna točka do na vrh Mali Vran. Sa vrha se proteže lijep pogled na planine oko Tomislavgrada dok se s druge strane lijepo vide vizure litica Velike Čvrsnice.",
    "thumbnail": "images/hiking-trail-vran-mountain-omrcenica-mali-vran-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja s Omrčenice vodi na Mali Vran."
  },
  {
    "id": 27,
    "slug": "hiking-trail-bogodol-velika-vlajina-cabulja-mountain-bosnia-and-herzegovina",
    "name": "Bogodol – Velika Vlajina (Čabulja)",
    "area": "Čabulja",
    "mountain": "Čabulja",
    "distanceKm": 14,
    "elevationM": 950,
    "durationH": 7.5,
    "startLat": 43.44900,
    "startLon": 17.65439,
    "routeType": "Povratna (isti put)",
    "destinations": ["Čabulja"],
    "tags": ["Mostar", "Vrdi", "Bogodol", "Miljenko Bošnjak", "Gonđuša", "Velika Vlajina", "Čabulja"],
    "description": "Najljepši vidikovac na Kanjoj Drežanke se može doživjeti upravo s vrha Velika Vlajina na Čabulji. Litice koje se strmoglavo spuštaju u dolinu dok vi stojite na rubu su nezaboravno iskustvo u planinarskom svijetu.",
    "thumbnail": "images/hiking-trail-cabulja-mountain-bogodol-velika-vlajina-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja iz Bogodola vodi na najviši vrh Čabulje, Veliku Vlajinu."
  },
  {
    "id": 28,
    "slug": "hiking-trail-vilino-polje-medvjed-cabulja-mountain-bosnia-and-herzegovina",
    "name": "Vilino Polje - Medvjed (Čabulja)",
    "area": "Čabulja",
    "mountain": "Čabulja",
    "distanceKm": 10.5,
    "elevationM": 830,
    "durationH": 7,
    "startLat": 43.48014,
    "startLon": 17.71125,
    "routeType": "Kružna",
    "destinations": ["Čabulja"],
    "tags": ["Vrdi", "Vilino Polje", "Medvjed", "Čabulja", "Dobrulj", "Drežnica"],
    "description": "Šarolika planinarska staza koja vodi uz litice Čabulje podno vrha Medvjed. Lijepi vidikovci, bujna šuma, izvori i zlatne ribice spojeni u jedno. Kružno spuštanje je najbolja opcija.",
    "thumbnail": "images/hiking-trail-cabulja-mountain-vilino-polje-medvjed-bosnia-and-herzegovina.jpg",
    "alt": "Šarolika planinarska staza koja vodi na vrh Medvjed na Čabulji."
  },
  {
    "id": 29,
    "slug": "hiking-trail-sedlo-bobotov-kuk-crno-jezero-durmitor-mountain-montenegro",
    "name": "Sedlo - Bobotov Kuk - Crno Jezero (Durmitor)",
    "area": "Durmitor",
    "mountain": "Durmitor",
    "distanceKm": 15,
    "elevationM": 950,
    "durationH": 9,
    "startLat": 43.09877,
    "startLon": 19.05086,
    "routeType": "Kružna",
    "destinations": ["Durmitor"],
    "tags": ["Durmitor", "Zeleni Vir", "Bobotov Kuk", "Crno Jezero", "Đevojka", "Katun Lokvice", "Sedlo", "Škrčko jezero", "Žabljak"],
    "description": "Hodanje jednom od najljepših planina na Balkanu, Durmitoru, vrijedi svakog koraka. Ova staza polazi sa sedla do najvišeg vrha, Bobotova Kuka. Natrag ide na drugu stranu prema Crnom Jezeru. Ovim silaskom se spusti 1250m/nv dok se prema gore prijeđe 950m/nv.",
    "thumbnail": "images/hiking-trail-durmitor-mountain-sedlo-bobotov-kuk-crno-jezero-montenegro.jpg",
    "alt": "Planinarska staza na Durmitoru u Crnoj Gori. Najljepša planinarska staza u Crnoj Gori u blizini grada Žabljaka."
  },
  {
    "id": 30,
    "slug":"hiking-trail-makar-vosac-biokovo-mountain-croatia",
    "name": "Makar - Vošac (Biokovo)",
    "area": "Biokovo",
    "mountain": "Biokovo",
    "distanceKm": 11,
    "elevationM": 1300,
    "durationH": 8,
    "startLat": 43.30006,
    "startLon": 17.02845,
    "routeType": "Povratna (isti put)",
    "destinations": ["Biokovo"],
    "tags": ["Makar", "Biokovo", "Vošac", "Makarska", "Park prirode Biokovo"],
    "description": "Planinarska staza koja vodi južnim, strmijim licem Biokova. Iz mjesta Makar, iznad Makarske pa sve do na vrh Vošac se ide uz litice označenim planinarskim putem. Čista uživancija dok se uspinje uz litice a Makarska rivijera kao na dlanu.",
    "thumbnail": "images/hiking-trail-biokovo-mountain-makar-vosac-croatia.jpg",
    "alt": "Planinarska staza koja iz mjesta Makar, iznad Makarske vodi do vrha Vošac na Biokovu."
  },
  {
    "id": 31,
    "slug": "hiking-trail-mostarska-bijela-lupoglav-prenj-mountain-bosnia-and-herzegovina",
    "name": "Lupoglav iz Mostarske Bijele (Prenj)",
    "area": "Prenj",
    "mountain": "Prenj",
    "distanceKm": 21,
    "elevationM": 2000,
    "durationH": 13,
    "startLat": 43.48987,
    "startLon": 17.80662,
    "routeType": "Povratna (isti put)",
    "destinations": ["Prenj"],
    "tags": ["Prenj", "Mostarska Bijela", "Grabovčići", "Barni Do", "Lupoglav", "Mostar"],
    "description": "Najteža planinarska staza u BiH a možda i na cijelom Balkanu. Uspon na Lupoglav iz Mostarske Bijele i natrag u jednom danu zahtijeva ogroman napor. Lijepa šuma i vizure Prenja s vrha su kao nagrada za sav trud.",
    "thumbnail": "images/hiking-trail-prenj-mountain-mostarska-bijela-lupoglav-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja iz Mostarske Bijele vodi na Lupoglav. Planinarska staza na Prenju blizu Mostara."
  },
  {
    "id": 32,
    "slug": "hiking-trail-vitlenica-veliki-kuk-cvrsnica-mountain-bosnia-and-herzegovina",
    "name": "Veliki Kuk iz Vitlenice (Čvrsnica)",
    "area": "Čvrsnica",
    "mountain": "Čvrsnica",
    "distanceKm": 17,
    "elevationM": 800,
    "durationH": 9,
    "startLat": 43.67330,
    "startLon": 17.62268,
    "routeType": "Povratna (isti put)",
    "destinations": ["Čvrsnica"],
    "tags": ["Čvrsnica", "Fratrova Kapa", "Veliki Kuk", "Vilinac", "Vitlenica", "Zaglavlje", "Vidikovac"],
    "description": "Znate li da Veliki Kuk ima čak 1300m visoke litice? A znate li da na te litice vodi planinarska staza? Veliki Kuk je najimpresivnije mjesto na cijelim Dinaridima. Stajati na vrhu, uz rub tih litica je neponovljiv osjećaj. Prolazi se i pored Pl. doma Vilinac gdje je i izvor.",
    "thumbnail": "images/hiking-trail-cvrsnica-mountain-vitlenica-veliki-kuk-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja sa Vitlenice vodi do ruba najviših litica na Balkanu. Litice Velikog Kuka na Čvrsnici."
  },
  {
    "id": 33,
    "slug": "hiking-trail-konjicka-bijela-osobac-prenj-mountain-bosnia-and-herzegovina",
    "name": "Konjička Bijela - Osobac (Prenj)",
    "area": "Prenj",
    "mountain": "Prenj",
    "distanceKm": 20,
    "elevationM": 1550,
    "durationH": 11,
    "startLat": 43.59270,
    "startLon": 17.94154,
    "routeType": "Povratna (isti put)",
    "destinations": ["Prenj"],
    "tags": ["Prenj", "Konjička Bijela", "Jezerce", "Osobac", "Konjic", "Taraš"],
    "description": "Zahtjevna planinarska staza koja vodi iz Konjičke Bijele do vrha Osobac. Cijelo vrijeme jako strmo dok se ne iziđe do Pl. skloništa Jezerce pored kojeg izvire i planinska voda. U blizini su i divlji konji a dolina pruža najljepše od Prenj planine, baš kao i pogled s vrha.",
    "thumbnail": "images/hiking-trail-prenj-mountain-konjicka-bijela-osobac-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja iz Konjičke Bijele vodi na vrh Osobac na Prenj planini. Planinarska staza u blizini Konjica u Bosni i Hercegovini."
  },
  {
    "id": 34,
    "slug": "hiking-trail-tri-izvora-plive-sipovo-city-bosnia-and-herzegovina",
    "name": "Tri izvora Plive (Šipovo)",
    "area": "Šipovo",
    "mountain": "Šipovo",
    "distanceKm": 4.5,
    "elevationM": 80,
    "durationH": 2,
    "startLat": 44.23914,
    "startLon": 17.02351,
    "routeType": "Kružna",
    "destinations": ["Šipovo"],
    "tags": ["Šipovo", "Pliva", "Izvori", "Janjske Otoke", "Vaganska Pećina"],
    "description": "Kružna, ne-markirana staza koja spaja tri lijepa izvora rijeke Plive. Iako nema markacija, staza je dobro utabana. Tri jaka izvora vode u okrilju bujne šume.",
    "thumbnail": "images/hiking-trail-sipovo-city-tri-izvora-plive-bosnia-and-herzegovina.jpg",
    "alt": "obilazak tri izvora Rijeke Plive pored Šipova. U blizini su i Janjske Otoke."
  },
  {
    "id": 35,
    "slug": "hiking-trail-vidikovac-iznad-masne-luke-cvrsnica-mountain-bosnia-and-herzegovina",
    "name": "Vidikovac iznad Masne Luke",
    "area": "Čvrsnica",
    "mountain": "Čvrsnica",
    "distanceKm": 2,
    "elevationM": 140,
    "durationH": 2,
    "startLat": 43.63548,
    "startLon": 17.55200,
    "routeType": "Povratna (isti put)",
    "destinations": ["Čvrsnica"],
    "tags": ["Čvrsnica", "Blidinje", "Masna Luka", "Badnji", "Vidikovac", "Munika", "Orlovača", "Lisac"],
    "description": "Jako lijep vidikovac na Masnu Luku koji se nalazi svega 40min hodanja od vikendica u podnožju Čvrsnice. Pogled na Crkvu sv. Ilije i više predjele Čvrsnice uz malo planinarenja.",
    "thumbnail": "images/hiking-trail-cvrsnica-mountain-vidikovac-iznad-masne-luke-bosnia-and-herzegovina.jpg",
    "alt": "Vidikovac na Čvrsnici s kojeg se pruža pogled na Masnu Luku u Parku prirode Blidinje."
  },
  {
    "id": 36,
    "slug": "hiking-trail-diva-grabovica-zlijeb-cvrsnica-mountain-bosnia-and-herzegovina",
    "name": "Diva Grabovica - Žlijeb (Čvrsnica)",
    "area": "Čvrsnica",
    "mountain": "Čvrsnica",
    "distanceKm": 9.5,
    "elevationM": 740,
    "durationH": 4.5,
    "startLat": 43.60433,
    "startLon": 17.69973,
    "routeType": "Povratna (isti put)",
    "destinations": ["Čvrsnica"],
    "tags": ["Diva Grabovica", "Žlijeb", "Čvrsnica", "Plasa", "Tise", "Mustafa Begović"],
    "description": "Planinarska staza koja vodi do jako lijepog vidikovca na Čvrsnici. U srcu Kanjona Diva Grabovica, malo iznad 1000m/nv se smjestilo ovo mjesto do kojeg vodi put koji je idealan čak i za početnike. Pogled se prostire na visoke litice koje krase ovaj kanjon.",
    "thumbnail": "images/hiking-trail-cvrsnica-mountain-diva-grabovica-zlijeb-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja vodi do vidikovca na Žlijebu, na planini Čvrsnici."
  },
  {
    "id": 37,
    "slug": "hiking-trail-vitlenica-pestibrdo-cvrsnica-mountain-bosnia-and-herzegovina",
    "name": "Vitlenica - Peštibrdo (Čvrsnica)",
    "area": "Čvrsnica",
    "mountain": "Čvrsnica",
    "distanceKm": 29,
    "elevationM": 1700,
    "durationH": 14,
    "startLat": 43.67329,
    "startLon": 17.62269,
    "routeType": "Povratna (isti put)",
    "destinations": ["Čvrsnica"],
    "tags": ["Vitlenica", "Peštibrdo", "Vilinac", "Ledeno Jezero", "Peharovi stanovi", "Kulidžanov stan", "Čvrsnica", "Janjičar vrelo"],
    "description": "Ova tura je pravi izazov za sve planinare. Dijelom što je jako zahtjevno a dijelom što dio puta nije obilježen. Peštibrdo je najudaljeniji dio Čvrsnice a po mnogima i najljepši.",
    "thumbnail": "images/hiking-trail-cvrsnica-mountain-vitlenica-pestibrdo-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja sa Vitlenice vodi na Peštibrdo, na planini Čvrsnici."
  },
  {
    "id": 38,
    "slug": "hiking-trail-lokvicicka-jezera-imotski-city-croatia",
    "name": "Tura oko Lokvičićkih Jezera (Imotski)",
    "area": "Imotski",
    "mountain": "Imotski",
    "distanceKm": 7,
    "elevationM": 480,
    "durationH": 4.5,
    "startLat": 43.48289,
    "startLon": 17.10581,
    "routeType": "Kružna",
    "destinations": ["Imotski"],
    "tags": ["Imotski", "Lokvičićka Jezera", "Proložac", "Prološko Blato", "Dalmatinska Zagora"],
    "description": "Da dalmatinska zagora krije mnoga čuda pokazati će vam i ova lijepo osmišljena planinarska staza koja prolazi pored nekoliko većih i manjih jezera u blizini Imotskog.",
    "thumbnail": "images/hiking-trail-imotski-city-lokvicicka-jezera-croatia.jpg",
    "alt": "Planinarska staza koja prolazi pored Lokvičićkih jezera u blizini Imotskog."
  },
  {
    "id": 39,
    "slug": "hiking-trail-paric-detelas-vito-visocica-mountain-bosnia-and-herzegovina",
    "name": "Visočica (vrhovi Parić, Detelaš i Vito)",
    "area": "Visočica",
    "mountain": "Visočica",
    "distanceKm": 11,
    "elevationM": 630,
    "durationH": 6,
    "startLat": ,
    "startLon": ,
    "routeType": "Kružna",
    "destinations": ["Visočica"],
    "tags": ["Visočica", "Bivak Zoran Šimić", "Parić", "Vito", "Detelaš", "Stećci"],
    "description": "Tri vrha, oštar greben, nekropole stećaka, bivak Zoran Šimić s lijepim pogledom i divna prostrana dolina. Sve to u jednoj kružnoj stazi. Najbolje vrijeme za ići je 5-i ili 6-i mjesec, jer su potoci na Visočici tada bujni zbog topljenja snijega",
    "thumbnail": "images/hiking-trail-visocica-mountain-paric-detelas-vito-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza na planini Visočici koja vodi do vrha Vito."
  },
  {
    "id": 40,
    "slug": "hiking-trail-omis-kula-omiska-dinara-mountain-croatia",
    "name": "Omiš - Luda Kuća - Kula (Omiška Dinara)",
    "area": "Omiš",
    "mountain": "Omiš",
    "distanceKm": 5,
    "elevationM": 520,
    "durationH": 4.5,
    "startLat": ,
    "startLon": ,
    "routeType": "Povratna (isti put)",
    "destinations": ["Omiš"],
    "tags": ["Omiš", "Imber", "Dalmacija", "Luda Kuća", "Kula", "Cetina"],
    "description": "Kameni krš Omiške Dinare odmah iznad lijepog grada Omiša. Luda Kuća uz stazu do na najviši vrh Kula. S jedne strane Jadransko more i Otoci a s druge omiško zaleđe i dalmatinska zagora.",
    "thumbnail": "images/hiking-trail-omiska-dinara-mountain-omis-kula-croatia.jpg",
    "alt": "Planinarska staza iznad grada Omiša koja vodi na najviši vrh Omiške Dinare."
  },
  {
    "id": 41,
    "slug": "hiking-trail-fortica-fortress-omiska-dinara-mountain-croatia",
    "name": "Tvrđava Fortica iznad Omiša",
    "area": "Omiš",
    "mountain": "Omiš",
    "distanceKm": 1.6,
    "elevationM": 260,
    "durationH": 1.75,
    "startLat": ,
    "startLon": ,
    "routeType": "Povratna (isti put)",
    "destinations": ["Omiš"],
    "tags": ["Fortica", "Omiš", "Omiška Dinara"],
    "description": "Jedna kratka planinarska staza koja kroz borovu šumu vodi do tvrđave Fortica. Iz grada Omiša do tvrđave se dođe za manje od sat vremena. Najidealnije za promatrati zalazak sunca.",
    "thumbnail": "images/hiking-trail-omiska-dinara-mountain-fortica-fortress-croatia.jpg",
    "alt": "Planinarska staza koja vodi iz grada Omisa do tvrđave Fortica."
  },
  {
    "id": 42,
    "slug": "hiking-trail-pazjatva-cave-omis-city-croatia",
    "name": "Špilja Pazjatva (Omiško zaleđe)",
    "area": "Omiš",
    "mountain": "Omiš",
    "distanceKm": 4,
    "elevationM": 220,
    "durationH": 2,
    "startLat": ,
    "startLon": ,
    "routeType": "Povratna (isti put)",
    "destinations": ["Omiš"],
    "tags": ["Gata", "Čisla", "Pazjatva", "Omiš", "Omiško Zaleđe", "Cetina"],
    "description": "Omiško zaleđe krije mnoge tajne ali i lijepa, skrovita mjesta. Jedno takvo je i špilja Pazjatva s koje se pruža lijep pogled na završni kilometar rijeke Cetine prije ušća u Jadransko More.",
    "thumbnail": "images/hiking-trail-omis-city-pazjatva-cave-croatia.jpg",
    "alt": "Staza koja vodi do šplije Pazjatva u zaleđu grada Omiša, iznad rijeke Cetine."
  },
  {
    "id": 43,
    "slug": "hiking-trail-podzavelim-kolakovac-zavelim-mountain-bosnia-and-herzegovina",
    "name": "Podzavelim - Kolakovac (Zavelim)",
    "area": "Zavelim",
    "mountain": "Zavelim",
    "distanceKm": 4.5,
    "elevationM": 540,
    "durationH": 4.5,
    "startLat": ,
    "startLon": ,
    "routeType": "Povratna (isti put)",
    "destinations": ["Zavelim"],
    "tags": ["Podzavelim", "Vir", "Kolakovac", "Zavelim"],
    "description": "Ako ste za jedno kraće planinarenje s otvorenim vidicima cijelo vrijeme, onda je ova staza s južne strane Zavelima savršen izbor. S vrha se dobro vide dijelovi dalmatinske zagore i visoke bosanske i hercegovače planine.",
    "thumbnail": "images/hiking-trail-zavelim-mountain-podzavelim-kolakovac-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja iz Podzavelima vodi na Kolakovac, najviši vrh Zavelima."
  },
  {
    "id": 44,
    "slug": "hiking-trail-brina-canyon-posusje-city-bosnia-and-herzegovina",
    "name": "Kanjon Brine (kroz tunele)",
    "area": "Kanjon Brine",
    "mountain": "Kanjon Brine",
    "distanceKm": 15,
    "elevationM": 600,
    "durationH": 6,
    "startLat": ,
    "startLon": ,
    "routeType": "Kružna",
    "destinations": ["Kanjon Brine"],
    "tags": ["Ričina", "Stećci", "Kanjon Brine", "Radovanj", "Posušje", "Tribistovo"],
    "description": "Šarolika, netipična planinarska staza kakvu  nećete naći nigdje drugo. Dubok kanjon, hodanje uskim putem uz litice, prolazak kroz malene tunele i mogućnost Via Ferrate su samo dio onoga što ova staza ima. Povratak natrag dosta lakšim putem.",
    "thumbnail": "images/hiking-trail-posusje-city-brina-canyon-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja vodi Kanjonom Brine u blizini Posušja."
  },
  {
    "id": 45,
    "slug": "hiking-trail-podvelez-brasina-velez-mountain-bosnia-and-herzegovina",
    "name": "Podvelež - Brasina (Velež)",
    "area": "Velež",
    "mountain": "Velež",
    "distanceKm": 14.5,
    "elevationM": 990,
    "durationH": 7,
    "startLat": ,
    "startLon": ,
    "routeType": "Povratna (isti put)",
    "destinations": ["Velež"],
    "tags": ["Mostar", "Podvelež", "Brasina", "Velež"],
    "description": "U blizini Mostara i skywalka Fortica se nalazi i početna točka staze koja vodi na Brasinu, jedan od vrhova Veleža. Na vrhu su razoreni ostaci nekadašnje tv i radio postaje uništeni u ratu.",
    "thumbnail": "images/hiking-trail-velez-mountain-podvelez-brasina-bosnia-and-herzegovina.jpg",
    "alt": "planinarska staza koja iz Podveleža vodi na vrh Brasina, blizu Mostara."
  },
  {
    "id": 46,
    "slug": "hiking-trail-staza-hrvatskih-kraljeva-lib-mountain-bosnia-and-herzegovina",
    "name": "Staza Hrvatskih Kraljeva (Lib)",
    "area": "Lib",
    "mountain": "Lib",
    "distanceKm": 14,
    "elevationM": 700,
    "durationH": 6,
    "startLat": ,
    "startLon": ,
    "routeType": "Kružna",
    "destinations": ["Lib"],
    "tags": ["Vrlokuk", "Seonica", "Omolje", "Smiljevača", "Kongora", "Studena", "lib"],
    "description": "Tematska planinarska staza koja uz lijepu šetnju priča priče iz prošlosti. Povijesno važna planina i jako lijepa tura njenim obroncima do izletišta Studena s izvorom.",
    "thumbnail": "images/hiking-trail-lib-mountain-staza-hrvatskih-kraljeva-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja vodi obroncima Lib planine nazvana Staza Hrvatskih Kraljeva."
  },
  {
    "id": 47,
    "slug": "hiking-trail-kedzara-veliki-vran-vran-mountain-bosnia-and-herzegovina",
    "name": "Kedžara - Veliki Vran (Vran)",
    "area": "Vran",
    "mountain": "Vran",
    "distanceKm": 8.5,
    "elevationM": 800,
    "durationH": 5.5,
    "startLat": ,
    "startLon": ,
    "routeType": "Povratna (isti put)",
    "destinations": ["Vran"],
    "tags": ["Diva Grabovčeva", "Veliki Vran", "Vran", "Kedžara", "Prskalov Dolac"],
    "description": "S Kedžare do na Veliki Vran se dolazi jednom dobro označenom planinarskom stazom. Pogledi na Čvrsnicu dok se penjete prema gore plijene pažnjom.",
    "thumbnail": "images/hiking-trail-vran-mountain-kedzara-veliki-vran-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja s Kedžare vodi na najviši vrh Vran planine, Veliki Vran."
  },
  {
    "id": 48,
    "slug": "hiking-trail-vaganj-kurtagica-dolac-kamesnica-mountain-bosnia-and-herzegovina",
    "name": "Vaganj - Kurtagića Dolac (Kamešnica)",
    "area": "Kamešnica",
    "mountain": "Kamešnica",
    "distanceKm": 12.5,
    "elevationM": 440,
    "durationH": 4.5,
    "startLat": ,
    "startLon": ,
    "routeType": "Povratna (isti put)",
    "destinations": ["Kamešnica"],
    "tags": ["Vaganj", "Kurtagića Dolac", "Kamešnica", "Vilinske Stine", "Edo Retelj"],
    "description": "Najbolji način za iskoristiti dan za vikend a ne umoriti se mnogo je šetnja do Kurtagića Doca. U blizini Pl. skloništa su Vilinske Stine koje se moraju posjetiti.",
    "thumbnail": "images/hiking-trail-kamesnica-mountain-vaganj-kurtagica-dolac-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja s Vagnja vodi do Kurtagića Doca na planini Kamešnici."
  },
  {
    "id": 49,
    "slug": "hiking-trail-burnjaca-garjeta-kamesnica-mountain-bosnia-and-herzegovina",
    "name": "Burnjača i Garjeta (Kamešnica)",
    "area": "Kamešnica",
    "mountain": "Kamešnica",
    "distanceKm": 19.5,
    "elevationM": 820,
    "durationH": 8,
    "startLat": ,
    "startLon": ,
    "routeType": "Povratna (isti put)",
    "destinations": ["Kamešnica"],
    "tags": ["Kamešnica", "Edo Retelj", "Vaganj", "Burnjača", "Garjeta", "Kurtagića Dolac", "Vilinske Stine"],
    "description": "Planinarenjem do Kurtagića Doce se prolazi lijepim i pitomim dijelom Kamešnice. No ako to nije dovoljno produžite još dalje do Burnjače i Garjete preko visokog grebena.",
    "thumbnail": "images/hiking-trail-kamesnica-mountain-burnjaca-garjeta-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja s Vagnja, preko Kurtagića Doca vodi na Burnjaču i Garjetu na planini Kamešnici."
  },
  {
    "id": 50,
    "slug": "hiking-trail-scirovac-sveti-ilija-biokovo-mountain-croatia",
    "name": "Šćirovac i sv. Ilija (Biokovo)",
    "area": "Biokovo",
    "mountain": "Biokovo",
    "distanceKm": 15.5,
    "elevationM": 1600,
    "durationH": 10,
    "startLat": ,
    "startLon": ,
    "routeType": "Kružna",
    "destinations": ["Biokovo"],
    "tags": ["Bartulovići", "Pozjata", "Šćirovac", "Sv. Ilija", "Bast", "Biokovo"],
    "description": "Spremni za jedan ozbiljan planinarski izazov? Ako jeste onda će uspon na ove vrhove iz smjera Bartulovića sa spustom u Bast testirati vaše psiho-fizičke planinarske sposobnosti.",
    "thumbnail": "images/hiking-trail-biokovo-mountain-scirovac-sveti-ilija-croatia.jpg",
    "alt": "Planinarska staza koja spaja vrhove Šćirovac i Sv. Ilija na Biokovu."
  },
  {
    "id": 51,
    "slug": "hiking-trail-posusje-velika-gradina-radovanj-mountain-bosnia-and-herzegovina",
    "name": "Posušje - Velika Gradina (Radovanj)",
    "area": "Radovanj",
    "mountain": "Radovanj",
    "distanceKm": ,
    "elevationM": ,
    "durationH": ,
    "startLat": ,
    "startLon": ,
    "routeType": "Povratna (isti put)",
    "destinations": ["Radovanj"],
    "tags": ["Gornji Jukići", "Posušje", "Velika Gradina", "Snjižnica", "Radovanj"],
    "description": "Iznad Posušja, prateći makadamski put se uspinje i planinarska staza koja vodi na vrh iznad grada. Pored odašiljača i antena na vrhu se lijepo uprizoruju i zalasci sunca.",
    "thumbnail": "images/hiking-trail-radovanj-mountain-posusje-velika-gradina-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja iz Posušja vodi na Veliku Gradinu, jedan od dva vrha Radovnja."
  },
  {
    "id": 52,
    "slug": "hiking-trail-kupres-stozer-mountain-bosnia-and-herzegovina",
    "name": "Vrh Stožera od Kupreške Kuće",
    "area": "Stožer",
    "mountain": "Stožer",
    "distanceKm": ,
    "elevationM": ,
    "durationH": ,
    "startLat": ,
    "startLon": ,
    "routeType": "Kružna",
    "destinations": ["Stožer"],
    "tags": ["Kupreška Kuća", "Snježna Kraljica", "Stožer", "Kupres"],
    "description": "Iznenadili bi se koliko je ova tura životopisna i puna sadržaja. Usponom uz padine Ski-Staze, kafe barom na vrhu i silaskom uz jako dotjeranu planinarsku stazu pod krošnjama će upotpuniti vaš dan. Na pola puta prema dolje je i vrelo s pitkom vodom.",
    "thumbnail": "images/hiking-trail-stozer-mountain-kupres-bosnia-and-herzegovina.jpg",
    "alt": "Kružna planinarska staza koja vss vodi po planini Stožer iznad Kupresa."
  },
  {
    "id": 53,
    "slug": "hiking-trail-matinski-vis-zepce-city-bosnia-and-herzegovina",
    "name": "Matinski Vis (Pl. dom - vrh)",
    "area": "Matinski Vis",
    "mountain": "Matinski Vis",
    "distanceKm": ,
    "elevationM": ,
    "durationH": ,
    "startLat": ,
    "startLon": ,
    "routeType": "Povratna (isti put)",
    "destinations": ["Matinski Vis"],
    "tags": ["Žepče", "Matinski Vis", "Sv. Bernard"],
    "description": "Lijep planinarski dom na Matinskom Visu je polazna točka za više lijepih staza. Ova vodi na najviši vrh na kojem je i kapelica sv. Bernarda. Na vrhu su i znakovi za oprez od minskih polja.",
    "thumbnail": "images/hiking-trail-zepce-city-matinski-vis-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja od planinarskog dom vodi na najvišu točku Matinskog Visa u Žepču."
  },
  {
    "id": 54,
    "slug": "hiking-trail-munika-veliki-vilinac-cvrsnica-mountain-bosnia-and-herzegovina",
    "name": "Munika - Veliki Vilinac (Čvrsnica)",
    "area": "Čvrsnica",
    "mountain": "Čvrsnica",
    "distanceKm": ,
    "elevationM": ,
    "durationH": ,
    "startLat": ,
    "startLon": ,
    "routeType": "Povratna (isti put)",
    "destinations": ["Čvrsnica"],
    "tags": ["Munika", "Orlovača", "Čvrsnica", "Blidinje", "Veliki Vilinac"],
    "description": "Manje poznati predio Čvrsnice između Mandine Plane i Orlovače krije i lijep dubok kanjon. Njime prolazi i staza kojom se može i na Veliki Vilinac. Na stazi je i Kenjčevo Vrelo.",
    "thumbnail": "images/hiking-trail-cvrsnica-mountain-munika-veliki-vilinac-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja od planinarske kuće Munika vodi na Veliki Vilinac ns planini Čvrsnici."
  },
  {
    "id": 55,
    "slug": "hiking-trail-diva-grabovica-strmenica-masna-luka-cvrsnica-mountain-bosnia-and-herzegovina",
    "name": "Diva Grabovica - Strmenica - Masna Luka",
    "area": "Čvrsnica",
    "mountain": "Čvrsnica",
    "distanceKm": ,
    "elevationM": ,
    "durationH": ,
    "startLat": ,
    "startLon": ,
    "routeType": "Kružna",
    "destinations": ["Čvrsnica"],
    "tags": ["Diva Grabovica", "Žlijeb", "Tise", "Trinjača", "Strmenica", "Hajdučka Vrata", "Veliki Vilinac", "Pršulje", "Masna Luka"],
    "description": "Ovakva planinarska tura je samo za najizdržljivije. Strmenici kao da nikada nema kraja a silazak u Masnu Luku traje kao vječnost.",
    "thumbnail": "images/hiking-trail-cvrsnica-mountain-diva-grabovica-strmenica-masna-luka-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja iz Dive Grabovice, preko Žlijeba, Strmenice, Hajdučkih Vrata i Velikog Vilinca vodi u Masnu Luku."
  },
  {
    "id": 56,
    "slug": "hiking-trail-sajkovici-troglav-dinara-mountain-bosnia-and-herzegovina",
    "name": "Sajkovići - Troglav (Dinara)",
    "area": "Dinara",
    "mountain": "Dinara",
    "distanceKm": ,
    "elevationM": ,
    "durationH": ,
    "startLat": ,
    "startLon": ,
    "routeType": "Kružna",
    "destinations": ["Dinara"],
    "tags": ["Sajkovići", "Mery Staza", "Troglav", "Dinara"],
    "description": "Planinarska staza koja iznad sela Sajkovići, Mery stazom vodi na najviši vrh Dinare, Troglav. Uspon kroz Kuolar podno najviših vrhova a spust natrag lakšom dionicom.",
    "thumbnail": "images/hiking-trail-dinara-mountain-sajkovici-troglav-bosnia-and-herzegovina.jpg",
    "alt": "Planinarska staza koja iznad sela Sajkovići, Mery stazom vodi na najviši vrh Dinare, Troglav."
  }
  ];
